Repository Quasar-13/Quasar-13, pull requests merged in 2021-04, with the labels that each got.

#50 removes hop qm cartdrige
  code/game/objects/items/devices/PDA/cart.dm
Labels: Fix, Jones PR, Speedmerge

#54 Lavaland medical area upgrades
  _maps/map_files/Mining/Lavaland.dmm
Labels: Speedmerge, Tweak

#48 Pubby and Boxstation
  ModularBungalow/SecuritySpecialist/healthsec.dm
  _maps/_basemap.dm
  _maps/boxstation.json
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Mining/Icemoon.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/pubbystation.json
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/game/area/space_station_13_areas.dm
  code/game/machinery/stasis.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  config/maps.txt
  icons/obj/machines/stasis.dmi
Labels: Feature, Map Things, Test Merged

#56 Maint monster changes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Things, Speedmerge, Tweak

#57 QM fix
  code/modules/jobs/job_types/quartermaster.dm
Labels: Fix, Speedmerge

#58 Jungle mining
  _maps/boxstation.json
  _maps/map_files/Mining/Jungle.dmm
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/datums/mapgen/JungleGenerator.dm
  code/datums/mapgen/biomes/_biome.dm
  code/game/turfs/open/floor/plating/planet.dm
Labels: Feature, Map Things, Speedmerge

#59 Adds heliostation for admins only
  _maps/_basemap.dm
  _maps/heliostation.json
  _maps/map_files/Heliostation/Heliostation.dmm
  config/maps.txt
Labels: Feature, Map Things, Speedmerge

#62 glowstick/flashlight in your box
  code/game/objects/items/storage/boxes.dm
Labels: Speedmerge, Tweak

#61 fix
  code/__DEFINES/monkeys.dm
  code/datums/ai/monkey/monkey_behaviors.dm
  code/datums/ai/monkey/monkey_controller.dm
  code/modules/food_and_drinks/restaurant/generic_venues.dm
  code/modules/food_and_drinks/restaurant/venue.dm
Labels: Fix, Jones PR, Speedmerge

#66 Names guns cooler
  ModularBungalow/bungalowWeapons/energy.dm
  ModularTegustation/tegu_captaingun.dm
  ModularTegustation/tegu_security_code/tegu_starter_gear.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/sniper.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Tweak

#67 Armbands and fix pins
  code/modules/clothing/under/accessories.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Feature, Fix, Speedmerge

#68 Gives tator laser gun implants better names
  code/modules/surgery/organs/augments_arms.dm
Labels: Speedmerge, Tweak

#69 Updates README.MD
  .github/assets/discord.png
  .github/assets/tegustation.png
  README.md
Labels: Documentation, Speedmerge

#63 Cloning. You know, for Voidtechs
  ModularBungalow/Cloning/_DEFINES/DNA.dm
  ModularBungalow/Cloning/_DEFINES/brain_trauma.dm
  ModularBungalow/Cloning/_DEFINES/machines.dm
  ModularBungalow/Cloning/_DEFINES/poll_ignore.dm
  ModularBungalow/Cloning/brain_item.dm
  ModularBungalow/Cloning/circuits.dm
  ModularBungalow/Cloning/computer.dm
  ModularBungalow/Cloning/countdown.dm
  ModularBungalow/Cloning/exp_cloner.dm
  ModularBungalow/Cloning/gas.dm
  ModularBungalow/Cloning/machine.dm
  ModularBungalow/Cloning/negative_mood.dm
  ModularBungalow/Cloning/traits.dm
  ModularBungalow/ruins/interdyne.dmm
  ModularBungalow/zbungalowicons/cloning/cloning.dmi
  ModularBungalow/zbungalowicons/cloning/cloning_pod.dmi
  ModularBungalow/zbungalowicons/cloning/cryo_mobs.dmi
  _maps/map_files/debug/runtimestation.dmm
  code/__DEFINES/DNA.dm
  code/__DEFINES/machines.dm
  code/_globalvars/lists/poll_ignore.dm
  code/datums/dna.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/clothing/head/misc_special.dm
  tgstation.dme
Labels: Feature

#72 Quickfix to the Geneticist
  code/modules/jobs/job_types/geneticist.dm
Labels: Speedmerge, Tweak

#74 Sets the X-02 to the HOP
  ModularBungalow/bungalowWeapons/energy.dm
  ModularTegustation/tegu_locker_overwrites.dm
  _maps/map_files/generic/CentCom.dmm
  code/game/gamemodes/objective_items.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/projectile/beams.dm
  icons/obj/projectiles.dmi
Labels: Speedmerge, Tweak

#75 Gives engineers, and only engineers a drill
  ModularTegustation/tegu_jobs/Voidtech/voidtech.dm
  code/game/objects/items/storage/belt.dm
Labels: Speedmerge, Tweak

#6 Alt job titles
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/bungalowconfig.dm
  ModularTegustation/tegu_global_vars.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/job.dm
  code/datums/datacore.dm
  code/datums/outfit.dm
  code/game/machinery/computer/crew.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/inventory.dm
  config/config.txt
  tgstation.dme
Labels: Feature, Jones PR

#83 Box and Meta stations bug fixes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Speedmerge

#82 Job title minor changes
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularTegustation/tegu_global_vars.dm
Labels: Speedmerge, Tweak

#78 Cloner malfunctions
  ModularBungalow/Cloning/circuits.dm
  ModularBungalow/Cloning/machine.dm
  ModularBungalow/Cloning/trauma.dm
  tgstation.dme
Labels: Jones PR, Tweak

#76 Blood dries with time and is less sticky to boots.
  code/datums/components/bloodysoles.dm
  code/datums/quirks/good.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
Labels: Feature, Test Merged, Tweak

#89 Phobos Station
  _maps/map_files/PhoboStation/PhoboStation.dmm
  _maps/phobostation.json
Labels: Affront to God, Feature, Map Things, Speedmerge

#91 Medical Overhaul V1 (Surgery Quickfix)
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/surgery_helpers.dm
  code/modules/surgery/tools.dm
Labels: Speedmerge, Tweak

#93 Weekly Hotfix
  ModularTegustation/tegu_captaingun.dm
  ModularTegustation/tegu_jobs/Voidtech/voidtech.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/machinery/stasis.dm
Labels: Speedmerge, Tweak

#52 Remora station
  _maps/_basemap.dm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  _maps/remorastation.json
  config/maps.txt
Labels: Feature, Map Things

#95 Prepares all the mining, good to go, baby
  ModularBungalow/Mining/items.dm
  ModularBungalow/Mining/monster.dm
  ModularBungalow/Mining/rockplanet.dm
  _maps/_basemap.dm
  _maps/deltastation.json
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Mining/Jungle.dmm
  _maps/map_files/Mining/Rockplanet.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/packedstation.json
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/datums/mapgen/biomes/_biome.dm
  tgstation.dme
Labels: Feature, Map Things, Speedmerge

#96 [PORT] Adds cryopods.
  code/controllers/subsystem/job.dm
  code/datums/mind.dm
  code/game/area/space_station_13_areas.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/announcement_system.dm
  code/game/machinery/cryopod.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/client/client_defines.dm
  icons/obj/machines/cryopod.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/CryopodConsole.js
Labels: Feature, Test Merged

#80 Cybernetic Organ Quirks
  ModularBungalow/cyberorgans.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/eyes.dm
  tgstation.dme
Labels: Feature, Jones PR

#97 [PORT] Adds an automatic transfer vote
  ModularBungalow/transfervote/code/readme.md
  ModularBungalow/transfervote/code/shuttle.dm
  ModularBungalow/transfervote/code/transfervote.dm
  ModularBungalow/transfervote/code/transfervote_config.dm
  code/controllers/subsystem/vote.dm
  code/modules/shuttle/emergency.dm
  config/config.txt
  tgstation.dme
Labels: Feature, Test Merged

#100 Duplicate "#include" hurts my brain
  tgstation.dme
Labels: Fix, Speedmerge

#94 Floor Sprite changes
  icons/turf/floors.dmi
Labels: Test Merged, Tweak

#104 Update floors.dmi
  icons/turf/floors.dmi
Labels: Fix, Gives GBP, Speedmerge

#105 Ensmallened Remora's Main halls
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Speedmerge, Tweak

#106 Adds Tidalmoon to Metastation
  _maps/map_files/Mining/Tidalmoon.dmm
  _maps/metastation.json
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
Labels: Feature, Map Things, Speedmerge

#103 Rebalances 5 C3 Chems
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Speedmerge, Tweak

#107 Changes some clothing around, adds new beret.
  ModularTegustation/tegu_locker_overwrites.dm
  code/modules/clothing/head/misc.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Speedmerge, Tweak

#84 Kiriechem V1 and the chemical Researcher
  ModularBungalow/Kiriechem/reagent.dm
  ModularBungalow/Kiriechem/reagentselector.dm
  ModularBungalow/Kiriechem/recipes.dm
  ModularBungalow/Kiriechem/vaechem.dm
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularTegustation/Teguicons/cards.dmi
  ModularTegustation/Teguicons/kirie_stuff/chemre.dmi
  ModularTegustation/Teguicons/kirie_stuff/chemreworn.dmi
  ModularTegustation/Teguicons/teguhud.dmi
  ModularTegustation/tegu_beefmen/code/modules/mob/beefman.dm
  ModularTegustation/tegu_beefmen/code/modules/mob/beefman_clothing.dm
  ModularTegustation/tegu_clothes_code/digisuits.dm
  ModularTegustation/tegu_clothes_code/wintercoats.dm
  ModularTegustation/tegu_digitigrade/lizardpeople_tegu.dm
  ModularTegustation/tegu_global_vars.dm
  ModularTegustation/tegu_jobs/chemre/chemresearcher.dm
  ModularTegustation/tegu_jobs/chemre/crClothing.dm
  ModularTegustation/tegu_jobs/job_integration.dm
  code/__DEFINES/misc.dm
  code/controllers/subsystem/persistence.dm
  code/datums/quirks/negative.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/cargo/bounties/reagent.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/pharmacist.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  code/modules/uplink/uplink_items.dm
  code/modules/vending/wardrobes.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
  tgstation.dme
Labels: Feature, Test Merged

#109 Adds Chemist spawn to all maps, and adds in areas for them.
  ModularTegustation/tegu_jobs/chemre/chemresearcher.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/game/area/space_station_13_areas.dm
  icons/turf/areas.dmi
Labels: Fix, Map Things, Speedmerge

#111 Adds ruins to Jungle and Rockplanet
  ModularBungalow/bungalowWeapons/energy.dm
  _maps/RandomRuins/JungleRuins/jungle_pizzawave.dmm
  _maps/RandomRuins/RockRuins/rockplanet_heirophant.dmm
  _maps/RandomRuins/RockRuins/rockplanet_soviet.dmm
  _maps/map_files/Mining/Rockplanet.dmm
  code/__DEFINES/maps.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/mapping.dm
  code/datums/ruins/jungle.dm
  code/datums/ruins/rockplanet.dm
  code/modules/admin/verbs/debug.dm
  config/game_options.txt
  tgstation.dme
Labels: Feature, Gives GBP, Map Things, Speedmerge, Tweak

#118 Ports updated readme
  ModularTegustation/README.md
Labels: Documentation

#113 Med stuff
  code/__DEFINES/nitrile.dm
  code/__DEFINES/traits.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/gloves/color.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/library/skill_learning/skillchip.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reagent_containers/medigel.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  tgstation.dme
Labels: Feature, Speedmerge

#114 A non-functional heart no longer causes heart attack if you have Muscled Veins
  code/modules/surgery/organs/heart.dm
Labels: Fix, Speedmerge

#116 Atmospherics Envirogloves are no longer insulated.
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Speedmerge, Tweak

#115 DNA.dm file Spring cleaning
  code/__DEFINES/DNA.dm
Labels: Documentation

#120 Fixes comments, the defines file, and comments out haunted dice.
  ModularBungalow/Cloning/_DEFINES/DNA.dm
  ModularBungalow/Cloning/_DEFINES/machines.dm
  ModularBungalow/Cloning/_DEFINES/poll_ignore.dm
  ModularBungalow/Cloning/brain_item.dm
  ModularBungalow/Cloning/computer.dm
  ModularBungalow/Cloning/exp_cloner.dm
  ModularTegustation/README.md
  ModularTegustation/tegu_beefmen/code/modules/mob/beefman.dm
  ModularTegustation/tegu_traitor_code/haunted_dice.dm
  ModularTegustation/tegu_traitor_code/uplink_items_tegu.dm
  code/__DEFINES/DNA.dm
  code/__DEFINES/TeguDefines.dm
  code/__DEFINES/__BungalowDefines.dm
  code/__DEFINES/machines.dm
  code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Documentation

#121 Gives voidtechs an engineering skillchip
  ModularTegustation/tegu_jobs/Voidtech/voidtech.dm
Labels: Jones PR, Speedmerge, Tweak

#117 Atmospherics Envirohelmets now have the same fire protection as the Atmospherics Hardsuit Helmet
  code/modules/clothing/spacesuits/plasmamen.dm
Labels: Fix

#122 Weekly hotfix
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/bungalowWeapons/energy.dm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/controllers/subsystem/persistence.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
Labels: Fix, Speedmerge

#123 A large amount of ruins
  _maps/RandomRuins/JungleRuins/jungle_nest.dmm
  _maps/RandomRuins/JungleRuins/jungle_pizzawave.dmm
  _maps/RandomRuins/JungleRuins/jungle_seedling.dmm
  _maps/RandomRuins/RockRuins/rockplanet_clock.dmm
  _maps/RandomRuins/RockRuins/rockplanet_clowncrash.dmm
  _maps/RandomRuins/RockRuins/rockplanet_cult.dmm
  _maps/RandomRuins/RockRuins/rockplanet_dangerpod.dmm
  _maps/RandomRuins/RockRuins/rockplanet_pioneer.dmm
  _maps/RandomRuins/RockRuins/rockplanet_pod.dmm
  _maps/RandomRuins/RockRuins/rockplanet_tradepost.dmm
  _maps/RandomRuins/RockRuins/rockplanet_wizard.dmm
  code/datums/ruins/jungle.dm
  code/datums/ruins/rockplanet.dm
Labels: Map Things, Speedmerge

#125 Balances shit
  ModularBungalow/bungalowWeapons/ballistics.dm
  ModularBungalow/martial/cqcrating.dm
  ModularBungalow/martial/cqcskillchip.dm
  ModularBungalow/zbungalowicons/kirie_stuff/kiriepistols.dmi
  code/__DEFINES/__BungalowDefines.dm
  code/__DEFINES/melee.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/mob/living/living_defense.dm
  tgstation.dme
Labels: Speedmerge, Tweak

#126 More labcoats
  ModularTegustation/Teguicons/kirie_stuff/chemre.dmi
  ModularTegustation/Teguicons/kirie_stuff/chemreworn.dmi
  ModularTegustation/tegu_jobs/chemre/crClothing.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/vending/wardrobes.dm
Labels: Feature, Speedmerge

#127 Alt Jobs revengance
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularTegustation/tegu_global_vars.dm
  code/modules/clothing/suits/armor.dm
Labels: Feature, Fix, Speedmerge

#128 Slapstick ports
  code/__DEFINES/_click.dm
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/projectiles.dm
  code/_onclick/drag_drop.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/fullauto.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/events/brain_trauma.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/ammunition/caseless/misc.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/energy/tesla.dm
  icons/effects/mouse_pointers/weapon_pointer.dmi
  tgstation.dme
Labels: Feature, Speedmerge

#79 ChimeraStation.
  ModularBungalow/Drinks_and_food/drinks_code.dm
  ModularBungalow/Drinks_and_food/drinks_food_Crafting_menu.dm
  _maps/_basemap.dm
  _maps/chimerastation.json
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  code/game/area/space_station_13_areas.dm
  config/maps.txt
  icons/turf/areas.dmi
Labels: Feature, Map Things

#129 ChimeraStation minor changes
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Fix, Map Things

#130 ChimeraStation more fixes part 2
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Fix, Gives GBP, Speedmerge

#135 ChimeraStation Fixes part 3
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Fix, Speedmerge

#134 Refactors the labcoats into "Neocoats"
  ModularBungalow/Clothing/neocoat.dm
  ModularBungalow/Clothing/parade.dm
  ModularBungalow/zbungalowicons/clothing/newlabcoats.dmi
  ModularBungalow/zbungalowicons/clothing/newlabcoats_worn.dmi
  ModularTegustation/Teguicons/kirie_stuff/chemre.dmi
  ModularTegustation/Teguicons/kirie_stuff/chemreworn.dmi
  ModularTegustation/tegu_jobs/chemre/chemresearcher.dm
  ModularTegustation/tegu_jobs/chemre/crClothing.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/pharmacist.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/vending/wardrobes.dm
  tgstation.dme
Labels: Tweak

#136 Remora fix, again
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Fix, Speedmerge

#112 New cargo crates + Black Market Goodies
  ModularBungalow/cargopacks/blackmarket.dm
  ModularBungalow/cargopacks/goodies.dm
  ModularBungalow/cargopacks/newinstances.dm
  ModularBungalow/cargopacks/packs.dm
  tgstation.dme
Labels: Feature, Test Merged

#92 RBMK - Really feel-the-nuke by making the station into the next Pripyat (new engine)
  ModularTegustation/Teguicons/reactor/computer.dmi
  ModularTegustation/Teguicons/reactor/control_rod.dmi
  ModularTegustation/Teguicons/reactor/inflatable.dmi
  ModularTegustation/Teguicons/reactor/rbmk.dmi
  ModularTegustation/Teguicons/reactor/reactor_parts.dmi
  ModularTegustation/Tegusounds/rmbk/alarm.ogg
  ModularTegustation/Tegusounds/rmbk/crane_1.wav
  ModularTegustation/Tegusounds/rmbk/falloutwind.ogg
  ModularTegustation/Tegusounds/rmbk/meltdown.ogg
  ModularTegustation/Tegusounds/rmbk/reactor_hum.ogg
  ModularTegustation/Tegusounds/rmbk/startup.ogg
  ModularTegustation/Tegusounds/rmbk/startup2.ogg
  ModularTegustation/Tegusounds/rmbk/switch.ogg
  ModularTegustation/Tegusounds/rmbk/switch2.ogg
  ModularTegustation/Tegusounds/rmbk/switch3.ogg
  ModularTegustation/Tegusounds/rmbk/turbine_end.ogg
  ModularTegustation/Tegusounds/rmbk/turbine_mid.ogg
  ModularTegustation/Tegusounds/rmbk/turbine_start.ogg
  ModularTegustation/tegu_rmbk/code/modules/cargo/exports/engineering.dm
  ModularTegustation/tegu_rmbk/code/modules/cargo/rmbkpacks.dm
  ModularTegustation/tegu_rmbk/code/modules/mining/shelters.dm
  ModularTegustation/tegu_rmbk/code/modules/mining/survival_pod.dm
  ModularTegustation/tegu_rmbk/code/modules/power/reactor/fuel_rods.dm
  ModularTegustation/tegu_rmbk/code/modules/power/reactor/rbmk.dm
  ModularTegustation/tegu_rmbk/code/modules/power/reactor/reactor_cargo.dm
  _maps/_basemap.dm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/rbmktest/rbmktest.dmm
  _maps/rbmktest.json
  _maps/templates/rbmk_1.dmm
  _maps/templates/rbmk_pod.dmm
  code/__DEFINES/sound.dm
  code/__HELPERS/matrices.dm
  config/maps.txt
  sound/misc/bikehorn_creepy.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/NtosRbmkStats.js
  tgui/packages/tgui/interfaces/RbmkControlRods.js
  tgui/packages/tgui/interfaces/RbmkStats.js
Labels: Feature, Test Merged

#138 elmo with a ak47
  ModularTegustation/Teguicons/tegu_guns.dmi
  ModularTegustation/tegu_ak47/akm_rifles.dm
  code/modules/cargo/packs.dm
  tgstation.dme
Labels: Feature, Gives GBP, Speedmerge

#137 adds sci neocoat
  ModularBungalow/Clothing/neocoat.dm
  ModularBungalow/zbungalowicons/clothing/newlabcoats.dmi
  ModularBungalow/zbungalowicons/clothing/newlabcoats_worn.dmi
  code/modules/jobs/job_types/scientist.dm
  code/modules/vending/wardrobes.dm
Labels: Fix, Speedmerge

#71 Ports 2 engineering-related /tg/ PRs
  code/__DEFINES/construction.dm
  code/__HELPERS/construction.dm
  code/__HELPERS/icons.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/RCD.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/closed/wall/material_walls.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/turf.dm
  icons/obj/atmospherics/components/hypertorus.dmi
  sound/items/rcdscan.ogg
  tgstation.dme
Labels: Feature, Jones PR
