Repository Quasar-13/Quasar-13, pull requests merged in 2021-12, with the labels that each got.

#354 Fixes mechs shooting themselves
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Fix

#355 Galaxy improvements
  ModularBungalow/Secure_lockers.dm
  ModularTegustation/Teguicons/tegucontraband.dmi
  _maps/map_files/GalaxyStation/Galaxystation.dmm
  _maps/map_files/GalaxyStation/Galaxystation_LVL2.dmm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/structures/door_assembly_types.dm
  icons/obj/doors/airlocks/station/commandwhite.dmi
Labels: Feature, Fix

#356 Fixes crash bug
  code/modules/research/nanites/nanite_programmer.dm
Labels: Speedmerge, Fix

#327 [ready] Beepeople, pollen, family heirlom, beecommon language .
  code/__DEFINES/food.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/names.dm
  code/controllers/subsystem/traumas.dm
  code/datums/quirks/negative.dm
  code/game/machinery/scan_gate.dm
  code/game/objects/items/plushes.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/language/beecommon.dm
  code/modules/language/language_holder.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/beeperson.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/surgery/advanced/wingreconstruction.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/tails.dm
  code/modules/surgery/organs/tongue.dm
  config/game_options.txt
  icons/ass/assbee.png
  icons/misc/language.dmi
  icons/mob/bee_antennae.dmi
  icons/mob/beetail.dmi
  icons/mob/beewings.dmi
  icons/mob/human.dmi
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/obj/plushes.dmi
  icons/obj/surgery.dmi
  sound/voice/bee/beescream.ogg
  sound/voice/bee/funnybeescream.ogg
  sound/weapons/beeattack.ogg
  sound/weapons/beemissattack.ogg
  strings/names/bee_first.txt
  strings/names/bee_last.txt
  tgstation.dme
Labels: Feature, Kirie Seal Of Approval (trademarked)

#351 Plasmamen can wear hats
  code/__DEFINES/obj_flags.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/hydroponics/beekeeping/beekeeper_suit.dm
Labels: Feature, Kirie Seal Of Approval (trademarked)

#347 Minor Synth balance changes + Shakes up our roundstarts
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  config/game_options.txt
Labels: Balance

#353 Adjusts the colors slighlty on the galaxy's captain's carapiece
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/worn/paradew.dmi
Labels: Sprites

#357 Fixes 05/12/21
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/bungalowWeapons/_icon/energy.dmi
  ModularTegustation/Teguicons/teguhud.dmi
  ModularTegustation/tegu_global_vars.dm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  _maps/map_files/RemusFacility/RemusFacility.dmm
  code/modules/jobs/job_types/voidtech.dm
  icons/mob/hud.dmi
  tgstation.dme
Labels: Speedmerge, Fix, Balance

#359 Solgov Suit v2
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/paradew.dmi
  ModularBungalow/clothing/worn/underw.dmi
  _maps/map_files/RemusFacility/RemusFacility.dmm
Labels: Feature, Speedmerge

#340 Turf fires from horizion
  code/__DEFINES/is_helpers.dm
  code/controllers/subsystem/turf_fire.dm
  code/game/machinery/firealarm.dm
  code/game/objects/effects/turf_fire.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  icons/effects/turf_fire.dmi
  tgstation.dme
Labels: Feature, Kirie Seal Of Approval (trademarked)

#360 Adds NT Blacksite Armor for future use
  ModularBungalow/blacksite/loadout/marine.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/ntblacksite.dm
  ModularBungalow/clothing/worn/coatw.dmi
  tgstation.dme
Labels: Feature, Sprites

#361 Hotfixes VT hardsuit
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/head.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/headw.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  tgstation.dme
Labels: Speedmerge, Fix

#363 Adds Medical professor Alt title
  ModularBungalow/altjobtitles/alt_titles.dm
Labels: Speedmerge, Tweak

#365 Adds fox tails from jollystation
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/surgery/organs/tails.dm
  icons/mob/mutant_bodyparts.dmi
Labels: Feature, Speedmerge

#366 Updates Jellypeople looks
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  config/game_options.txt
  icons/mob/human_parts_greyscale.dmi
Labels: Tweak, Sprites

#372 Adds Commodore's gloves
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/icons/gloves.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/glovesw.dmi
  _maps/map_files/generic/CentCom.dmm
Labels: Feature, Speedmerge, Sprites

#374 Samurai outfit
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/underw.dmi
Labels: Feature, Speedmerge

#368 NT Blacksite
  ModularBungalow/SecuritySpecialist/mechpilot.dm
  ModularBungalow/blacksite/loadout/deathsquad.dm
  ModularBungalow/blacksite/loadout/ert.dm
  ModularBungalow/blacksite/loadout/marine.dm
  ModularBungalow/blacksite/loadout/turrets.dm
  ModularBungalow/blacksite/medicbag.dm
  ModularBungalow/blacksite/shotgun.dm
  ModularBungalow/blacksite/turret.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/ntblacksite.dm
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  _maps/_basemap.dm
  _maps/map_files/NTBlacksite/NTBlacksite.dmm
  _maps/ntblacksite.json
  _maps/templates/drekar.dmm
  code/__DEFINES/economy.dm
  code/__DEFINES/preferences.dm
  code/datums/datacore.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/!blacksite/bridge.dm
  code/modules/jobs/job_types/!blacksite/deathsquad.dm
  code/modules/jobs/job_types/!blacksite/ertcommander.dm
  code/modules/jobs/job_types/!blacksite/ertengineer.dm
  code/modules/jobs/job_types/!blacksite/ertmedic.dm
  code/modules/jobs/job_types/!blacksite/ertsecurity.dm
  code/modules/jobs/job_types/!blacksite/ntcommander.dm
  code/modules/jobs/job_types/!blacksite/ntleader.dm
  code/modules/jobs/job_types/!blacksite/ntmarine.dm
  code/modules/jobs/job_types/!blacksite/ntmedical.dm
  code/modules/jobs/job_types/!blacksite/ntoperator.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  config/maps.txt
  tgstation.dme
Labels: Feature

#364 Secretary buff
  code/modules/jobs/job_types/secretary.dm
Labels: Tweak

#376 6 MONTHS. SIX FUCKING MONTHS OF THIS CRAP I FINALLY FIXED IT
  ModularTegustation/Teguicons/cards.dmi
  _maps/andromedastation.json
  _maps/ntblacksite.json
  _maps/remusfacility.json
  code/modules/jobs/job_types/chemresearcher.dm
  icons/obj/card.dmi
Labels: Speedmerge, Fix

#352 Computer restyle
  ModularTegustation/tegu_rmbk/code/modules/power/reactor/rbmk.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/computer/pod.dm
  code/modules/events/pirates.dm
  code/modules/library/lib_machines.dm
  code/modules/power/solar.dm
  icons/obj/computer.dmi
  icons/obj/modular_console.dmi
  icons/obj/stock_parts.dmi
Labels: Sprites

#377 Chaos marine buff
  ModularTegustation/tegu_mobs/chaos_marine.dm
Labels: Balance

#378 Anomalous Weaponry & Tools
  ModularTegustation/Teguicons/bhole_projector.dmi
  ModularTegustation/anomaly_items/anomaly_tools.dm
  ModularTegustation/anomaly_items/anomaly_tools.dmi
  ModularTegustation/anomaly_items/anomaly_weapons.dm
  ModularTegustation/anomaly_items/research_nodes.dm
  tgstation.dme
Labels: Feature

#375 LUFR ruin tweaks
  ModularTegustation/Teguicons/tegucontraband.dmi
  ModularTegustation/tegu_factions/lufr.dm
  _maps/RandomRuins/LavaRuins/lavaland_surface_lufr_pod.dmm
Labels: Tweak

#382 Moth Plushes
  ModularBungalow/toys.dm
  ModularBungalow/zbungalowicons/toys.dmi
  _maps/map_files/generic/CentCom.dmm
  tgstation.dme
Labels: Feature, Sprites

#261 Casiostation (Reopen)
  _maps/_basemap.dm
  _maps/casiostation.json
  _maps/map_files/AndromedaStation/Andromeda2.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/CasioStation/Casiostation_new.dmm
  config/maps.txt
Labels: Feature, Map Things, Test Merged

#379 Guns Renaming 2: Blacksite 2
  ModularBungalow/blacksite/loadout/ert.dm
  ModularBungalow/bungalowWeapons/_icon/energy.dmi
  ModularBungalow/bungalowWeapons/energy.dm
  ModularBungalow/bungalowWeapons/mining.dm
  code/modules/jobs/job_types/!blacksite/ntoperator.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/vehicles/mecha/combat/marauder.dm
Labels: Feature, Balance, Sprites, Lore

#383 Fixes plush names
  ModularBungalow/toys.dm
  ModularBungalow/zbungalowicons/toys.dmi
Labels: Speedmerge, Fix

#387 Adds random mining
  ModularBungalow/randommining.dm
  _maps/boxstation.json
  _maps/casiostation.json
  _maps/chimerastation.json
  _maps/deltastation.json
  _maps/galaxystation.json
  _maps/kilostation.json
  _maps/metastation.json
  _maps/packedstation.json
  _maps/pubbystation.json
  code/__DEFINES/__BungalowDefines.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/random_mining.dm
  config/mining_levels.txt
  tgstation.dme
Labels: Feature, Balance

#388 Nerfs Chestbursting and AI Xenos
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
Labels: Speedmerge, Balance

#392 change a few names real quick
  code/modules/projectiles/guns/energy/laser.dm
Labels: Lore

#391 Adds in more Captain display cases, adds the shotgun into Pubby
  ModularBungalow/displaycase.dm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  tgstation.dme
Labels: Map Things, Speedmerge, Tweak

#386 ports 2 heretic changes from tg
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
Labels: Balance, Kirie Seal Of Approval (trademarked)

#393 Pistol resprite + CTF Rifle Sprite fix
  ModularBungalow/bungalowWeapons/_icon/ballistics.dmi
  ModularTegustation/Teguicons/kirie_stuff/kiriepistols.dmi
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Speedmerge, Sprites

#380 Gives the Administrator a nagant
  _maps/map_files/RemusFacility/RemusFacility.dmm
  code/game/objects/items/storage/belt.dm
Labels: Map Things, Tweak

#373 Tomb worlds
  ModularTegustation/Teguicons/96x32.dmi
  ModularTegustation/Teguicons/megafauna.dmi
  ModularTegustation/tegu_config.dm
  ModularTegustation/tegu_mobs/necromancer.dm
  ModularTegustation/tegu_mobs/necromancer_skeletons.dm
  _maps/RandomZLevels/tombs/necromancer.dmm
  _maps/map_files/Mining/Lavaland.dmm
  code/__DEFINES/achievements.dm
  code/controllers/subsystem/mapping.dm
  code/datums/achievements/boss_achievements.dm
  code/datums/achievements/boss_scores.dm
  code/datums/mind.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/pointed/necromancer_curse.dm
  code/modules/spells/spell_types/touch_attacks.dm
  code/modules/tomb_worlds/gate.dm
  code/modules/tomb_worlds/loot.dm
  code/modules/tomb_worlds/portal.dm
  code/modules/tomb_worlds/spawner.dm
  code/modules/tomb_worlds/zlevel.dm
  config/game_options.txt
  config/tomb_worlds.txt
  icons/UI_Icons/Achievements/Boss/necromancer.png
  icons/mob/actions/actions_spells.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/misc/touchspell_lefthand.dmi
  icons/mob/inhands/misc/touchspell_righthand.dmi
  icons/mob/simple_human.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/items_and_weapons.dmi
  tgstation.dme
Labels: Feature, Map Things, Sprites, Kirie Seal Of Approval (trademarked)

#394 Miner Hardsuit no longer slow as fucking balls
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Speedmerge, Balance

#389 Kiriechem V3
  ModularBungalow/Kiriechem/mixer.dm
  ModularBungalow/Kiriechem/reagent.dm
  ModularBungalow/Kiriechem/reagentselector.dm
  ModularBungalow/Kiriechem/recipes.dm
  ModularBungalow/Kiriechem/vaechem.dm
  code/__DEFINES/subsystems.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Feature, Test Merged

#396 Bugfixes 24/12/2021
  ModularBungalow/Secure_lockers.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/uplink/uplink_items.dm
Labels: Speedmerge, Fix

#399 Dextrous claw
  ModularTegustation/Tegusounds/claw/death.ogg
  ModularTegustation/tegu_mobs/the_claw.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
Labels: Tweak

#401 Gives Claw actual hands
  ModularTegustation/tegu_mobs/the_claw.dm
Labels: Speedmerge, Fix

#381 [NEEDS TM]Revolution Overhaul Part 1
  code/controllers/subsystem/job.dm
  code/datums/ert.dm
  code/game/gamemodes/revolution/revolution.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/revolution/revolution.dm
Labels: Test Merged, Balance

#402 Fixes 28/21/2021
  ModularBungalow/areas/station.dm
  ModularBungalow/clothing/hardsuit.dm
  ModularBungalow/clothing/icons/helmet.dmi
  _maps/map_files/CasioStation/Casiostation.dmm
  code/modules/jobs/job_types/!blacksite/ntleader.dm
  code/modules/jobs/job_types/!blacksite/ntmarine.dm
  code/modules/jobs/job_types/!syndicate/comandant.dm
  code/modules/jobs/job_types/!syndicate/deckhand.dm
  code/modules/jobs/job_types/!syndicate/first_officer.dm
  code/modules/jobs/job_types/!syndicate/logistics_officer.dm
  code/modules/jobs/job_types/!syndicate/marine.dm
  code/modules/jobs/job_types/!syndicate/mechanic.dm
  code/modules/jobs/job_types/!syndicate/medical_officer.dm
  code/modules/jobs/job_types/!syndicate/military_police.dm
  code/modules/jobs/job_types/!syndicate/military_warden.dm
  code/modules/jobs/job_types/!syndicate/pilot_officer.dm
  code/modules/jobs/job_types/!syndicate/requisitions_chief.dm
  code/modules/jobs/job_types/!syndicate/staff_officer.dm
  code/modules/jobs/job_types/!syndicate/triage_officer.dm
  code/modules/jobs/job_types/!syndicate/triage_technician.dm
  code/modules/jobs/job_types/!syndicate/wing_commander.dm
  code/modules/jobs/job_types/!terragov/administrator.dm
  code/modules/jobs/job_types/!terragov/bunker_crew.dm
  code/modules/jobs/job_types/!terragov/civilian.dm
  code/modules/jobs/job_types/!terragov/commander.dm
  code/modules/jobs/job_types/!terragov/engineer.dm
  code/modules/jobs/job_types/!terragov/lab_technician.dm
  code/modules/jobs/job_types/!terragov/medical_technician.dm
  code/modules/jobs/job_types/!terragov/security.dm
  code/modules/jobs/job_types/!terragov/soldier.dm
  icons/turf/areas.dmi
  interface/skin.dmf
  tgstation.dme
Labels: Fix

#406 Whitelists blueshield
  code/modules/jobs/job_types/!casio/blueshield.dm
Labels: Speedmerge, Tweak

#408 Adds firealarms to casiostation
  _maps/map_files/CasioStation/Casiostation.dmm
Labels: Map Things, Speedmerge

#409 Tweaks 30/12/21
  code/modules/jobs/job_types/!casio/blueshield.dm
  code/modules/jobs/job_types/!casio/ntcaptain.dm
  code/modules/jobs/job_types/!casio/ntleader.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/jobs.dm
  code/modules/mining/mine_items.dm
  code/modules/vending/security.dm
Labels: Speedmerge, Tweak

#404 Random rooms framework
  code/controllers/subsystem/mapping.dm
  code/game/objects/effects/spawners/roomspawners.dm
  code/modules/mapping/random_rooms.dm
  icons/effects/landmarks_static.dmi
  tgstation.dme
Labels: Feature

#400 Porting Breaching Shotguns
  ModularBungalow/bungalowWeapons/_icon/shotgunshell.dmi
  ModularBungalow/bungalowWeapons/ammocasing/ShotgunShells.dm
  ModularBungalow/bungalowWeapons/guns/shotguns.dm
  ModularBungalow/cargopacks/packs.dm
  ModularBungalow/zbungalowicons/weapons/shotguns.dmi
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/__DEFINES/projectiles.dm
  tgstation.dme
Labels: Feature

#410 Casio V2.1: Casio harder
  _maps/RandomRuins/RockRuins/rockplanet_heirophant.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/modules/jobs/job_types/!casio/blueshield.dm
  code/modules/jobs/job_types/!casio/ntpolice.dm
  code/modules/jobs/job_types/chemresearcher.dm
  code/modules/jobs/job_types/secretary.dm
  code/modules/jobs/job_types/voidtech.dm
  icons/obj/pda.dmi
Labels: Feature, Map Things, Speedmerge, Fix, Sprites

#411 Resprites the old and retro laser guns
  code/modules/projectiles/guns/energy/laser.dm
  icons/obj/guns/energy.dmi
Labels: Speedmerge, Sprites
