Repository Quasar-13/Quasar-13, pull requests merged in 2021-10, with the labels that each got.

#294 [PORT] moffins and seafood foodtype
  code/__DEFINES/construction.dm
  code/__DEFINES/food.dm
  code/__HELPERS/_lists.dm
  code/datums/components/crafting/crafting.dm
  code/game/objects/items/dyekit.dm
  code/game/objects/items/food/burgers.dm
  code/game/objects/items/food/lizard.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/food/snacks.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/trash.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_seafood.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/vending/snack.dm
  icons/obj/food/food.dmi
  icons/obj/janitor.dmi
  tgstation.dme
Labels: Speedmerge, Tweak

#292 Makes codebase compatible with 514
  code/game/objects/items/toy_mechs.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Cleanup

#300 LGBT Socks
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  icons/mob/clothing/underwear.dmi
Labels: Speedmerge, sprites

#301 Fixes the deployment bug
  _maps/map_files/Mining/mission_ice.dmm
Labels: Fix, Cleanup

#291 Adds T12 rifle and tweaks AK rifles
  ModularTegustation/Teguicons/48x32_guns.dmi
  ModularTegustation/Teguicons/magazines.dmi
  ModularTegustation/Teguicons/tegu_guns.dmi
  ModularTegustation/Tegusounds/weapons/guns/ak47.ogg
  ModularTegustation/Tegusounds/weapons/guns/autorifle-1.ogg
  ModularTegustation/Tegusounds/weapons/guns/autorifle-2.ogg
  ModularTegustation/Tegusounds/weapons/guns/autorifle-3.ogg
  ModularTegustation/tegu_ak47/akm_rifles.dm
  ModularTegustation/tegu_weapons/rifles.dm
  code/game/sound.dm
  tgstation.dme
Labels: Feature, Test Merged, Tweak

#304 nerfs chaos marine armor, buffs H.E.C.K. suit and removes the honk crystal
  ModularTegustation/tegu_mobs/chaos_marine.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Balance

#302 SMC Major changes
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/smc.dm
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  ModularTegustation/tegu_jobs/!syndicate/comandant.dm
  ModularTegustation/tegu_jobs/!syndicate/first_officer.dm
  ModularTegustation/tegu_jobs/!syndicate/medical_officer.dm
  ModularTegustation/tegu_jobs/!syndicate/military_warden.dm
  ModularTegustation/tegu_jobs/!syndicate/requisitions_chief.dm
  ModularTegustation/tegu_jobs/!syndicate/triage_officer.dm
  ModularTegustation/tegu_jobs/!syndicate/triage_technician.dm
  _maps/map_files/AndromedaStation/Andromeda.dmm
  _maps/map_files/Mining/mission_phobos.dmm
  code/modules/projectiles/projectile/special/neurotoxin.dm
  icons/obj/card.dmi
Labels: Map Things, Balance

#288 Protective clown's mask and a road sign
  ModularTegustation/Teguicons/mask_item.dmi
  ModularTegustation/Teguicons/mask_worn.dmi
  ModularTegustation/tegu_clothes_code/mask.dm
  ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm
  ModularTegustation/tegu_traitor_code/uplink_items_tegu.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/life.dm
  tgstation.dme
Labels: Feature, Test Merged

#299 Ports the TG screen PRs
  code/__DEFINES/flags.dm
  code/__DEFINES/preferences.dm
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/blob_overmind.dm
  code/_onclick/hud/families.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screentip.dm
  code/datums/status_effects/buffs.dm
  code/game/atoms.dm
  code/game/objects/effects/info.dm
  code/game/objects/items.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/openspace.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/status_bar/status_bar.dm
  interface/skin.dmf
  tgstation.dme
  tgui/packages/tgui-panel/index.js
Labels: Feature

#308 Fixes mad clown kit
  ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm
Labels: Fix

#293 Telescopic Batons and whips now have special effects for limbs; Stun Baton checks for armor.
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/stunbaton.dm
Labels: Balance

#296 Lizards United Front
  ModularTegustation/tegu_config.dm
  ModularTegustation/tegu_factions/lufr.dm
  ModularTegustation/tegu_posters.dm
  ModularTegustation/tegu_ruins/lavaland_ruins.dm
  ModularTegustation/tegu_traitor_code/objectives_tegu.dm
  ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm
  ModularTegustation/tegu_traitor_code/uplink_items_tegu.dm
  _maps/RandomRuins/LavaRuins/lavaland_surface_lufr_pod.dmm
  code/game/gamemodes/infiltration/infiltration.dm
  code/modules/antagonists/infiltrator/infiltrator.dm
  code/modules/antagonists/infiltrator/infiltrator_event.dm
  config/game_options.txt
  tgstation.dme
Labels: Feature

#289 Cloning fix/tweak
  ModularBungalow/Cloning/_DEFINES/brain_trauma.dm
  ModularBungalow/Cloning/circuits.dm
  ModularBungalow/Cloning/computer.dm
  ModularBungalow/Cloning/exp_cloner.dm
  ModularBungalow/Cloning/machine.dm
  code/modules/mob/living/carbon/human/human.dm
  tgstation.dme
Labels: Test Merged, Fix

#298 [WIP] The Claw
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/Tegusounds/claw/attack.ogg
  ModularTegustation/Tegusounds/claw/error.ogg
  ModularTegustation/Tegusounds/claw/eviscerate1.ogg
  ModularTegustation/Tegusounds/claw/eviscerate2.ogg
  ModularTegustation/Tegusounds/claw/move.ogg
  ModularTegustation/Tegusounds/claw/prepare.ogg
  ModularTegustation/tegu_mobs/the_claw.dm
  tgstation.dme
Labels: Feature, Kirie Seal Of Approval (trademarked)
