Repository Quasar-13/Quasar-13, pull requests merged in 2021-07, with the labels that each got.

#250 gives the seedling ruin a area
  _maps/RandomRuins/JungleRuins/jungle_seedling.dmm
Labels: Fix, Speedmerge

#248 adds the missing l in the wallcom off sprite
  icons/obj/vending.dmi
Labels: Fix, Speedmerge

#249 [PORT] Monkeys no longer rip apart machines from the inside
  code/datums/ai/monkey/monkey_behaviors.dm
Labels: Fix

#252 [PORT] wisps no longer fall in chasms
  code/datums/components/chasm.dm
Labels: Fix, Speedmerge

#240 [PORT] You can now clean pies off of your face in the sink
  code/datums/components/creamed.dm
Labels: Tweak

#216 Kiriechem V2: Hard Mode
  ModularBungalow/Kiriechem/mixer.dm
  ModularBungalow/Kiriechem/reagent.dm
  ModularBungalow/Kiriechem/reagentselector.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  tgstation.dme
Labels: Feature, Test Merged, Tweak

#257 moves a pubby engine room scrubber
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Gives GBP, Speedmerge, Tweak

#253 gives Chaos Marine a kill score
  ModularTegustation/tegu_mobs/chaos_marine.dm
  code/__DEFINES/achievements.dm
  code/datums/achievements/boss_achievements.dm
  code/datums/achievements/boss_scores.dm
  code/modules/asset_cache/asset_list_items.dm
  icons/UI_Icons/Achievements/Boss/marine.png
Labels: Feature, Test Merged

#237 removes carpotoxin scar reaction
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak

#242 [PORT] Lizard Food: a Taste of the Homeworld
  .vscode/settings.json
  code/__DEFINES/construction.dm
  code/__DEFINES/food.dm
  code/datums/components/crafting/crafting.dm
  code/datums/mapgen/CaveGenerator.dm
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/items/food/lizard.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/food/snacks.dm
  code/game/objects/items/trash.dm
  code/modules/aquarium/fish.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_lizard.dm
  code/modules/hydroponics/grown/korta_nut.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/vending/cola.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/snack.dm
  icons/obj/aquarium.dmi
  icons/obj/drinks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/food/lizard.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/growing_mushrooms.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/janitor.dmi
  icons/obj/lavaland/ash_flora.dmi
  tgstation.dme
Labels: Test Merged, Tweak

#265 Remora Fixes
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Fix, Map Things

#266 Map Fixes again
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Fix, Map Things, Speedmerge

#267 Adds the i
  ModularBungalow/Kiriechem/reagent.dm
  ModularBungalow/Kiriechem/reagentselector.dm
  ModularBungalow/Kiriechem/recipes.dm
Labels: Fix, Speedmerge

#227 [PORT] Fixes maint pill score not being tracked
  code/datums/achievements/misc_scores.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Feature, Test Merged

#255 Xenoarchaeology
  ModularBungalow/clothing/neocoat.dm
  ModularBungalow/structurescapsules/capsules.dm
  ModularBungalow/structurescapsules/structures.dm
  ModularBungalow/xenoarch/designs_and_tech.dm
  ModularBungalow/xenoarch/icons/mining.dmi
  ModularBungalow/xenoarch/icons/ore_visuals.dmi
  ModularBungalow/xenoarch/icons/xenoarch_items.dmi
  ModularBungalow/xenoarch/icons/xenoarch_machines.dmi
  ModularBungalow/xenoarch/readme.md
  ModularBungalow/xenoarch/strange_rock.dm
  ModularBungalow/xenoarch/xenoarch_item.dm
  ModularBungalow/xenoarch/xenoarch_machine.dm
  ModularBungalow/xenoarch/xenoarch_reward.dm
  ModularBungalow/xenoarch/xenoarch_tool.dm
  ModularBungalow/zbungalowicons/clothing/newlabcoats.dmi
  ModularBungalow/zbungalowicons/clothing/newlabcoats_worn.dmi
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/templates/workplace_xenoarch.dmm
  code/modules/mining/equipment/mineral_scanner.dm
  tgstation.dme
Labels: Feature
