Repository Quasar-13/Quasar-13, pull requests merged in 2021-11, with the labels that each got.

#317 nerfs bats and removes the player_minimum on scarp
  code/game/objects/items/weaponry.dm
  code/modules/uplink/uplink_items.dm
Labels: Speedmerge, Balance

#318 [PORT] Riot armor sprites
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Speedmerge, Sprites

#320 [PORT] Tend Wounds and Debride Infection surgeries now estimate how long you have left to finish
  code/__DEFINES/combat.dm
  code/datums/components/embedded.dm
  code/datums/elements/embed.dm
  code/datums/wounds/burns.dm
  code/game/machinery/Sleeper.dm
  code/modules/surgery/burn_dressing.dm
  code/modules/surgery/healing.dm
  tgstation.dme
Labels: Tweak

#321 [PORT] The Cycling 2.0, Airlocks can now be built in game to cycle and named
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/structures/door_assembly.dm
  code/game/turfs/open/floor.dm
  tgui/packages/tgui/interfaces/AirlockElectronics.js
Labels: Tweak

#322 [PORT] TGUI clip and notice boards
  code/game/objects/structures/noticeboard.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/Clipboard.js
  tgui/packages/tgui/interfaces/NoticeBoard.js
Labels: Tweak

#323 Multiple minor fixes
  ModularBungalow/altjobtitles/alt_titles.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Speedmerge, Fix

#325 Standard Issues plasmarines
  _maps/map_files/AndromedaStation/Andromeda.dmm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/security.dm
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/under/plasmaman.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/under/plasmaman.dmi
Labels: Balance, Kirie Seal Of Approval (trademarked)

#297 [TM only] Remus Facility
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/paradew.dmi
  ModularTegustation/tegu_global_vars.dm
  ModularTegustation/tegu_jobs/!syndicate/mess.dm
  ModularTegustation/tegu_jobs/!syndicate/ordtech.dm
  ModularTegustation/tegu_jobs/!syndicate/survivor.dm
  ModularTegustation/tegu_jobs/!terragov/administrator.dm
  ModularTegustation/tegu_jobs/!terragov/bunker_crew.dm
  ModularTegustation/tegu_jobs/!terragov/civilian.dm
  ModularTegustation/tegu_jobs/!terragov/commander.dm
  ModularTegustation/tegu_jobs/!terragov/engineer.dm
  ModularTegustation/tegu_jobs/!terragov/lab_technician.dm
  ModularTegustation/tegu_jobs/!terragov/medical_technician.dm
  ModularTegustation/tegu_jobs/!terragov/security.dm
  ModularTegustation/tegu_jobs/!terragov/soldier.dm
  _maps/_basemap.dm
  _maps/heliostation.json
  _maps/icebox.json
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Below.dmm
  _maps/map_files/PhoboStation/PhoboStation.dmm
  _maps/map_files/RemusFacility/RemusFacility.dmm
  _maps/phobostation.json
  _maps/remusfacility.json
  code/__DEFINES/preferences.dm
  code/datums/datacore.dm
  code/game/objects/items/cards_ids.dm
  code/game/turfs/open/floor/plating/planet.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/client/preferences.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/maps.txt
  icons/obj/card.dmi
  tgstation.dme
Labels: Feature, Test Merged

#326 Adds Spacer
  code/modules/language/language_holder.dm
  code/modules/language/spacer.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/surgery/organs/tongue.dm
  icons/misc/language.dmi
  tgstation.dme
Labels: Feature, Speedmerge

#328 Updates Neurotoxin to insta-down
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Speedmerge, Balance

#330 Plasmaman tanks can hold less volume, plasmamen need less plasma to breath properly
  code/__DEFINES/atmospherics.dm
  code/game/objects/items/tanks/tank_types.dm
  code/modules/surgery/organs/lungs.dm
Labels: Speedmerge, Balance, Kirie Seal Of Approval (trademarked)

#331 Default Plasmaman Envirosuit fix
  icons/mob/clothing/under/plasmaman.dmi
Labels: Speedmerge, Fix, Sprites

#329 Revert "Updates Neurotoxin to insta-down"
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Jones PR, Balance

#333 hopefully adds "NT-Military Police"
  ModularBungalow/altjobtitles/alt_titles.dm
Labels: Tweak

#334 update chair sprites
  icons/obj/chairs.dmi
Labels: Sprites

#336 small packed changes
  _maps/map_files/PackedStation/PackedStation.dmm
Labels: Map Things, Speedmerge

#338 nerfs chaos marine's chainsword and replaces bubble's spellblade for ninja shoes
  ModularTegustation/tegu_mobs/chaos_marine.dm
  code/game/objects/structures/icemoon/cave_entrance.dm
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Removal, Balance

#324 Replaces our labcoats with the new labcoats
  ModularBungalow/clothing/berets.dm
  ModularBungalow/zbungalowicons/clothing/newlabcoats.dmi
  ModularBungalow/zbungalowicons/clothing/newlabcoats_worn.dmi
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#337 Security Titles
  ModularBungalow/altjobtitles/alt_titles.dm
Labels: Tweak

#343 Syndicate Corps Outfit overhaul and adds new alt title for captain
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/smc.dm
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/paradew.dmi
  ModularTegustation/tegu_jobs/!syndicate/comandant.dm
  ModularTegustation/tegu_jobs/!syndicate/marine.dm
  ModularTegustation/tegu_jobs/!syndicate/military_police.dm
  ModularTegustation/tegu_jobs/!syndicate/military_warden.dm
  code/modules/jobs/access.dm
  code/modules/tgui/USE_BUILD_BAT_INSTEAD_OF_DREAM_MAKER.dm
  icons/mob/clothing/suit.dmi
  icons/obj/card.dmi
  tgstation.dme
Labels: Feature, Speedmerge, Sprites

#341 SMC Major Balance changes
  _maps/map_files/AndromedaStation/Andromeda.dmm
Labels: Balance

#342 Chimera is now admin only.
  config/maps.txt
Labels: Map Things, Speedmerge

#344 Adds a sec cell on remus
  _maps/map_files/RemusFacility/RemusFacility.dmm
Labels: Map Things

#345 Clown Poster
  code/game/objects/effects/contraband.dm
  icons/obj/contraband.dmi
Labels: Speedmerge, Sprites

#309 Fixed Xenoarch, who broke this!?
  ModularBungalow/xenoarch/strange_rock.dm
Labels: Fix me, Speedmerge, Fix

#310 The Xenoarch update we needed.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Things, Tweak

#346 Swaps guns out, adds in research console.
  _maps/map_files/RemusFacility/RemusFacility.dmm
Labels: Map Things, Speedmerge, Balance

#348 Syndicate rank pins and formal wear
  ModularBungalow/clothing/accessory.dm
  ModularBungalow/clothing/icons/accessory.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/smc.dm
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/accessoryw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  ModularTegustation/Teguicons/tegucontraband.dmi
  ModularTegustation/tegu_jobs/!syndicate/requisitions_chief.dm
  ModularTegustation/tegu_posters.dm
  _maps/map_files/AndromedaStation/Andromeda.dmm
  code/game/objects/effects/contraband.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/language/spacer.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/under/centcom.dmi
  icons/obj/clothing/under/centcom.dmi
  icons/obj/contraband.dmi
  tgstation.dme
Labels: Feature, Sprites, Lore

#349 Edits Descriptions of Vests
  ModularBungalow/clothing/smc.dm
  code/modules/clothing/suits/armor.dm
Labels: Lore

#295 Respriting part 2: Guns
  ModularBungalow/bungalowWeapons/_icon/ballistics.dmi
  ModularBungalow/bungalowWeapons/_icon/energy.dmi
  ModularBungalow/bungalowWeapons/energy.dm
  ModularBungalow/bungalowWeapons/mining.dm
  ModularTegustation/Teguicons/tegu_guns.dmi
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Feature, Kirie Seal Of Approval (trademarked)
