Repository Quasar-13/Quasar-13, pull requests merged in 2021-09, with the labels that each got.

#263 [PORT] Changes the space adaptation sprite to something more subtle
  code/datums/mutations/space_adaptation.dm
  icons/effects/genetics.dmi
Labels: Tweak

#279 adds in-spect scanners to most maps missing them
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Speedmerge, Fix

#108 Mother Anarchy loves her sons.
  code/modules/admin/verbs/secrets.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  tgui/packages/tgui/interfaces/Secrets.js
Labels: Feature, Test Merged

#274 [PORT] Byond member ghost recolors can now have hair + accessories
  code/_globalvars/lists/flavor_misc.dm
Labels: Tweak

#282 [PORT] hair gradients
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/quirks/neutral.dm
  code/game/objects/items/dyekit.dm
  code/modules/cargo/goodies.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/vending/games.dm
  icons/mob/hair_gradients.dmi
  icons/obj/dyespray.dmi
  tgstation.dme
Labels: Feature

#286 Tiny Cybersun tweaks
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/jobs/jobs.dm
Labels: Tweak, balance

#283 Fixes(?) advanced hypnoflash
  ModularTegustation/tegu_traitor_code/tegu_traitor_items.dm
Labels: Speedmerge, Fix

#87 [READY] Adds new EVENT megafauna for events/when there is not enough FUN.
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/megafauna.dmi
  ModularTegustation/Teguicons/teguclothing_worn.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/Teguicons/teguitems_hold_left.dmi
  ModularTegustation/Teguicons/teguitems_hold_right.dmi
  ModularTegustation/Tegusounds/apostle/antagonist/rapture.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/rapture2.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/scythe.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/scythe_spell.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/spear.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/spear_charge.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/spear_dash.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/staff_charge.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/whisper.ogg
  ModularTegustation/Tegusounds/apostle/mob/apostle_bell.ogg
  ModularTegustation/Tegusounds/apostle/mob/apostle_death.ogg
  ModularTegustation/Tegusounds/apostle/mob/apostle_death_final.ogg
  ModularTegustation/Tegusounds/apostle/mob/apostle_heal.ogg
  ModularTegustation/Tegusounds/apostle/mob/apostle_shout.ogg
  ModularTegustation/Tegusounds/apostle/mob/apostle_spell.ogg
  ModularTegustation/tegu_items/apostle_items.dm
  ModularTegustation/tegu_mobs/apostle.dm
  ModularTegustation/tegu_mobs/apostle_antag.dm
  tgstation.dme
Labels: Feature, Test Merged

#290 Updates golem ship
  _maps/RandomRuins/AnywhereRuins/golem_ship.dmm
Labels: Map Things, Speedmerge

#285 more map changes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Mining/Jungle.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Things, Speedmerge

#284 [PORT] Adds a mapping helper that can cycle multiple airlocks regardless of location
  code/game/machinery/doors/airlock.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Map Things, Tweak

#280 [PORT] Adds visible age to examine_more
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#271 [PORT] Gives borgs the crew manifest NTOS app
  code/modules/modular_computers/computers/item/tablet_presets.dm
Labels: Fix

#281 Respriting part 1: Tools
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  code/game/machinery/iv_drip.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/theft_tools.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/surgery/tools.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_old_lefthand.dmi
  icons/mob/inhands/equipment/tools_old_righthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/chemical.dmi
  icons/obj/clothing/belt_old_overlays.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/defib.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/surgery.dmi
  icons/obj/syringe.dmi
  icons/obj/tools.dmi
  icons/obj/tools_old.dmi
  tgstation.dme
Labels: Feature, Map Things, Test Merged, Tweak, Cleanup
