Repository Quasar-13/Quasar-13, pull requests merged in 2021-06, with the labels that each got.

#220 [Jungle Mining] New ruins from Vae
  _maps/RandomRuins/JungleRuins/jungle_demon.dmm
  _maps/RandomRuins/JungleRuins/jungle_hangar.dmm
  _maps/RandomRuins/JungleRuins/jungle_pirate.dmm
  _maps/RandomRuins/JungleRuins/jungle_seedling.dmm
  _maps/RandomRuins/JungleRuins/jungle_skeleton.dmm
  _maps/RandomRuins/JungleRuins/jungle_spider.dmm
  _maps/RandomRuins/JungleRuins/jungle_syndicate.dmm
  _maps/RandomRuins/JungleRuins/jungle_village.dmm
  _maps/RandomRuins/JungleRuins/jungle_witch.dmm
  code/datums/ruins/jungle.dm
Labels: Feature, Map Things, Speedmerge

#222 adds more holopads to Remora
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Speedmerge

#223 reported map bugs
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Things, Speedmerge

#219 [PORT] Money put into PDA/Tablet will go into ID, if there is one in it.
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/modular_computers/computers/item/computer.dm
Labels: Feature

#224 The goose is no longer comparable to a Sherman tank. Mapping fixes included
  ModularBungalow/terry.dm
  ModularTegustation/Teguicons/closet.dmi
  _maps/_basemap.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PhoboStation/PhoboStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  _maps/map_files/rbmktest/rbmktest.dmm
  _maps/rbmktest.json
  code/modules/mob/living/simple_animal/friendly/dog.dm
  config/maps.txt
  goon/icons/mob/misc/birdterry.dmi
  tgstation.dme
Labels: Map Things, Speedmerge

#225 Removes Skyrat
  ModularBungalow/NTSL/code/modules/scripting/Implementations/Telecomms.dm
  ModularBungalow/emote_popup.dm
  ModularBungalow/gunpoint/code/datum/gunpoint/gunpoint.dm
  ModularBungalow/gunpoint/code/datum/gunpoint/gunpoint_datum.dm
  ModularBungalow/gunpoint/code/datum/gunpoint/gunpoint_radial.dm
  ModularBungalow/gunpoint/icons/radial_gunpoint.dmi
  ModularBungalow/gunpoint/icons/targeted.dmi
  ModularBungalow/gunpoint/readme.md
  ModularBungalow/gunpoint/sound/targetoff.ogg
  ModularBungalow/gunpoint/sound/targeton.ogg
  ModularBungalow/transfervote/code/transfervote.dm
  ModularBungalow/typingindicator/code/mob.dm
  ModularBungalow/typingindicator/icons/typing_indicator.dmi
  ModularBungalow/typingindicator/readme.md
  ModularBungalow/zbungalowicons/popup_flicks.dmi
  code/__DEFINES/__BungalowDefines.dm
  code/__DEFINES/~skyrat_defines/signals.dm
  code/__DEFINES/~skyrat_defines/traits.dm
  code/_onclick/click.dm
  code/_onclick/hud/radial.dm
  code/datums/dna.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_say.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/mob_say.dm
  tgstation.dme
Labels: Cleanup

#228 Makes the CO it's own thing
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/paradew.dmi
  ModularTegustation/Teguicons/cards.dmi
  code/modules/jobs/access.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Feature, Speedmerge

#208 Adding back budget cards in physical item
  ModularBungalow/budgetcard/deptartementcard.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  tgstation.dme
Labels: Feature, Test Merged

#166 TGUI Select Equipment
  code/__DEFINES/vv.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/persistence.dm
  code/datums/outfit.dm
  code/game/objects/items.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/outfit_editor.dm
  code/modules/admin/outfit_manager.dm
  code/modules/admin/outfits.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/selectequipment.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/under/_under.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/zombie/items.dm
  tgstation.dme
  tgui/packages/common/collections.js
  tgui/packages/tgui/interfaces/OutfitEditor.js
  tgui/packages/tgui/interfaces/OutfitManager.js
  tgui/packages/tgui/interfaces/SelectEquipment.js
Labels: Tweak

#226 [PORT] Cat Butcher changes
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
Labels: Feature, Test Merged

#204 You can stand in sofcrit, but not for long before colapsing if you take more damage
  code/__DEFINES/combat.dm
  code/__DEFINES/stat.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Test Merged, Tweak

#230 Keeps kids out of the game
  code/modules/admin/IsBanned.dm
Labels: Feature, Speedmerge

#229 Buffs Duffles
  code/game/objects/items/storage/backpack.dm
Labels: Speedmerge, Tweak

#232 Fernando's a failure, can't have shit in Detroit.
  code/modules/admin/IsBanned.dm
Labels: Cleanup, Speedmerge

#234 Adds the Blueshield as a choice in the console
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Feature, Speedmerge

#178 Medical Rework: Mind and Blood
  ModularBungalow/medical/bottles.dm
  ModularBungalow/medical/pills.dm
  ModularBungalow/medical/psychvendor.dm
  ModularBungalow/virology/buffs.dm
  ModularBungalow/virology/healing.dm
  ModularBungalow/zbungalowicons/medical/scanners.dmi
  ModularBungalow/zbungalowicons/vending.dmi
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/datums/diseases/advance/symptoms/heal.dm
  code/modules/jobs/job_types/psychologist.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/surgery/surgery_helpers.dm
  code/modules/surgery/surgery_step.dm
  code/modules/vending/medical.dm
  tgstation.dme
Labels: Feature, Fix me, Test Merged

#236 Hotfix 06/11
  ModularBungalow/Mining/rockplanet.dm
  ModularTegustation/Teguicons/cards.dmi
  _maps/map_files/CSSSStarfury.dmm
  _maps/metastation.json
  code/controllers/subsystem/job.dm
  icons/obj/card.dmi
  tgstation.dme
Labels: Fix, Speedmerge

#238 The scream PR
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/ethereal/ethereal_scream_1.ogg
  sound/voice/ethereal/ethereal_scream_2.ogg
  sound/voice/ethereal/ethereal_scream_3.ogg
  sound/voice/lizard/credits.txt
  sound/voice/lizard/lizard_scream_1.ogg
  sound/voice/lizard/lizard_scream_2.ogg
  sound/voice/lizard/lizard_scream_3.ogg
Labels: Feature, Test Merged

#247 [PORT] Adds skeleton and robot wings
  code/__DEFINES/is_helpers.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  icons/mob/clothing/wings.dmi
Labels: Feature, Speedmerge

#244 gives ash drake armor cold resistance also gives icemoon megafauna gps
  code/modules/clothing/suits/cloaks.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
Labels: Speedmerge, Tweak
