Repository Quasar-13/Quasar-13, pull requests merged in 2021-05, with the labels that each got.

#139 Fixed space in Engi hallway
  _maps/map_files/PackedStation/PackedStation.dmm
Labels: Fix, Map Things, Speedmerge

#141 NTSL Is added to the map
  ModularBungalow/NTSL/code/game/machinery/telecomms/computers/traffic_control.dm
  ModularBungalow/NTSL/code/modules/atmospherics/airalarm.dm
  ModularTegustation/tegu_jobs/secretary/secretary.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/__DEFINES/access.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/station_engineer.dm
Labels: Fix, Speedmerge, Tweak

#142 Buffs Biosuits and makes them usable over Hardsuits (and the VT hardsuit)
  ModularTegustation/tegu_jobs/Voidtech/voidtechClothing.dm
  ModularTegustation/tegu_locker_overwrites.dm
  code/modules/clothing/suits/bio.dm
Labels: Speedmerge, Tweak

#144 Tidal Moon is fixed
  _maps/_basemap.dm
  _maps/map_files/Mining/Tidalmoon.dmm
Labels: Fix, Map Things

#146 Remora upgrade
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Speedmerge, Tweak

#147 funny text changes
  strings/names/death_commando.txt
  strings/names/japanese_prefix.txt
  strings/sillytips.txt
  strings/tips.txt
Labels: Affront to God

#148 [PORT] some sprites
  code/modules/religion/religion_structures.dm
  icons/mob/clothing/under/costume.dmi
  icons/obj/candle.dmi
  icons/obj/clothing/under/costume.dmi
  icons/obj/hand_of_god_structures.dmi
  icons/obj/kitchen.dmi
  icons/obj/vending.dmi
Labels: Tweak

#151 better maint for ChimeraStation
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Tweak

#156 Removes Skeleton keys
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/storage/belt.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/machine_vending.dm
Labels: Speedmerge, Tweak

#161 [PORT] Cloaks
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/cloaks.dmi
Labels: Tweak

#153 [PORT] TGUI Select Equipment
  code/__DEFINES/vv.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/persistence.dm
  code/datums/outfit.dm
  code/game/objects/items.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/outfit_editor.dm
  code/modules/admin/outfit_manager.dm
  code/modules/admin/outfits.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/selectequipment.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/under/_under.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/zombie/items.dm
  tgstation.dme
  tgui/packages/common/collections.js
  tgui/packages/tgui/interfaces/OutfitEditor.js
  tgui/packages/tgui/interfaces/OutfitManager.js
  tgui/packages/tgui/interfaces/SelectEquipment.js
Labels: Feature

#168 Brig medic Coat
  ModularBungalow/Clothing/neocoat.dm
  ModularBungalow/NTSL/code/game/objects/items/devices/PDA/PDA_types.dm
  ModularBungalow/zbungalowicons/clothing/newlabcoats.dmi
  ModularBungalow/zbungalowicons/clothing/newlabcoats_worn.dmi
  code/modules/vending/wardrobes.dm
  icons/obj/pda.dmi
Labels: Feature

#171 Removes McGriff, Replaces with Terry.
  ModularBungalow/terry.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PhoboStation/PhoboStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  icons/mob/pets.dmi
  tgstation.dme
Labels: Feature, Speedmerge

#170 Andy, the paramedic goose
  ModularTegustation/tegu_mobs/andy.dm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  goon/icons/mob/misc/bird.dmi
  tgstation.dme
Labels: Affront to God

#173 ChimeraStation, better looks in some places, and small fixes
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Fix, Fix me, Speedmerge

#175 ChimeraStation, less empty maint, minor changes in kitchen and botany also tourist.
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Fix, Map Things, Speedmerge

#176 Remora station 15 MV Edition
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Feature, Map Things

#150 [PORT] Social Anxiety rework
  code/datums/quirks/negative.dm
Labels: Test Merged, Tweak

#187 Berets and the unatomized packed fixes.
  ModularBungalow/Clothing/berets.dm
  ModularBungalow/zbungalowicons/clothing/head.dmi
  ModularBungalow/zbungalowicons/clothing/head_worn.dmi
  ModularTegustation/tegu_jobs/deputies/deputy.dm
  ModularTegustation/tegu_locker_overwrites.dm
  _maps/map_files/PackedStation/PackedStation.dmm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/vending/wardrobes.dm
  tgstation.dme
Labels: Feature, Speedmerge

#181 makes combat medic kit have a sec access card
  ModularBungalow/SecuritySpecialist/specialist.dm
Labels: Jones PR, Tweak

#192 [PORT] Gives Geiger Counters a worn sprite
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/belt_mirror.dmi
Labels: Speedmerge, Tweak

#191 [PORT] new Herald sprites
  icons/mob/clothing/neck.dmi
  icons/mob/lavaland/lavaland_elites.dmi
  icons/obj/lavaland/elite_trophies.dmi
Labels: Speedmerge, Tweak

#189 Raven Cruiser shuttle console fix
  _maps/shuttles/emergency_raven.dmm
Labels: Fix, Speedmerge

#194 [PORT] Telescopic Baton Resprite
  icons/obj/items_and_weapons.dmi
Labels: Tweak

#195 New tips
  ModularBungalow/zbungalowicons/weapons/energy.dmi
  strings/tips.txt
Labels: Feature, Speedmerge

#198 Changed some sprites
  code/modules/surgery/organs/autosurgeon.dm
  icons/UI_Icons/Pills/pill1.png
  icons/UI_Icons/Pills/pill10.png
  icons/UI_Icons/Pills/pill7.png
  icons/UI_Icons/Pills/pill8.png
  icons/UI_Icons/Pills/pill9.png
  icons/obj/chemical.dmi
  icons/obj/device.dmi
  icons/obj/syringe.dmi
Labels: Speedmerge, Tweak

#196 [TM] SSD sleep
  code/modules/mob/living/life.dm
Labels: Feature

#162 New gamer walls
  icons/turf/walls/reinforced_wall.dmi
  icons/turf/walls/wall.dmi
  strings/sillytips.txt
  tgstation.dme
Labels: Test Merged, Tweak

#199 Changes T5 to be endgame, and Mining gun upgrades
  ModularBungalow/bungalowWeapons/energy.dm
  ModularBungalow/zbungalowicons/kirie_stuff/kiriepistols.dmi
  ModularTegustation/t5_parts.dm
  _maps/RandomRuins/SpaceRuins/Brokensolar.dmm
  _maps/RandomRuins/SpaceRuins/SpaceShower.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/abandonedteleporter.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/derelict1.dmm
  _maps/RandomRuins/SpaceRuins/derelict4.dmm
  _maps/RandomRuins/SpaceRuins/derelict5.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/hellfactory.dmm
  _maps/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/RandomRuins/SpaceRuins/mechtransport.dmm
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomRuins/SpaceRuins/smallsphere.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  code/modules/mining/machine_vending.dm
Labels: Feature, Speedmerge, Tweak

#200 Code cleaning
  ModularBungalow/Clothing/parade.dm
  ModularBungalow/NTSL/icons/mob/clothing/under/engineering.dmi
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/bungalowWeapons/_icon/ballistics.dmi
  ModularBungalow/bungalowWeapons/_icon/energy.dmi
  ModularBungalow/bungalowWeapons/_icon/miningguns.dmi
  ModularBungalow/bungalowWeapons/ammocasing/energy.dm
  ModularBungalow/bungalowWeapons/ballistics.dm
  ModularBungalow/bungalowWeapons/energy.dm
  ModularBungalow/bungalowWeapons/mining.dm
  ModularBungalow/bungalowWeapons/revolver.dm
  ModularBungalow/martial/cqcrating.dm
  ModularBungalow/zbungalowicons/kirie_stuff/kiriepistols.dmi
  ModularTegustation/Teguicons/kirie_stuff/chemreworn.dmi
  ModularTegustation/Teguicons/kirie_stuff/kiriepistols.dmi
  tgstation.dme
Labels: Cleanup, Speedmerge

#197 New ID Cards
  ModularTegustation/Teguicons/cards.dmi
  code/game/objects/items/emags.dm
  icons/obj/card.dmi
Labels: Test Merged, Tweak

#201 Marshal
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/neocoat.dm
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/specialist.dm
  ModularBungalow/clothing/worn/paradew.dmi
  ModularBungalow/zbungalowicons/clothing/parade.dmi
  ModularBungalow/zbungalowicons/clothing/paradeicon.dmi
  tgstation.dme
Labels: Feature, Speedmerge

#203 Mapfix for remora
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/paradew.dmi
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/cards_ids.dm
  code/modules/client/preferences.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/captain.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Fix, Map Things, Speedmerge

#205 fixes most issues in #182
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Speedmerge

#210 In theory this should fix alt click
  code/__HELPERS/mouse_control.dm
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/_onclick/drag_drop.dm
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/observer.dm
  code/_onclick/overmind.dm
  code/datums/components/fullauto.dm
  code/datums/components/tackle.dm
  code/datums/mutations/hulk.dm
  code/game/atoms.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/devices/laserpointer.dm
  code/game/objects/items/tail_pin.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/buildmode/bm_mode.dm
  code/modules/buildmode/buttons.dm
  code/modules/buildmode/submodes/advanced.dm
  code/modules/buildmode/submodes/area_edit.dm
  code/modules/buildmode/submodes/basic.dm
  code/modules/buildmode/submodes/boom.dm
  code/modules/buildmode/submodes/copy.dm
  code/modules/buildmode/submodes/delete.dm
  code/modules/buildmode/submodes/fill.dm
  code/modules/buildmode/submodes/mapgen.dm
  code/modules/buildmode/submodes/outfit.dm
  code/modules/buildmode/submodes/smite.dm
  code/modules/buildmode/submodes/throwing.dm
  code/modules/buildmode/submodes/variable_edit.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/client/client_procs.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets/lmg.dm
  code/modules/projectiles/projectile/energy/tesla.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/vehicles/mecha/_mecha.dm
Labels: Fix, Test Merged

#211 Adds in a bunch of clothes
  ModularBungalow/NTSL/code/modules/clothing/under/jobs/engineering.dm
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/paradew.dmi
  ModularTegustation/tegu_jobs/secretary/secretary.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/shoes/magboots.dm
  icons/mob/clothing/feet.dmi
  icons/obj/card.dmi
  icons/obj/clothing/shoes.dmi
Labels: Feature, Tweak

#209 Gunpoints and typing indicator - skyrat port
  code/__DEFINES/~skyrat_defines/signals.dm
  code/__DEFINES/~skyrat_defines/traits.dm
  code/_onclick/click.dm
  code/_onclick/hud/radial.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_say.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/mob_say.dm
  icons/mob/radial.dmi
  modular_skyrat/master_files/code/modules/mob/living/emote_popup.dm
  modular_skyrat/master_files/icons/mob/popup_flicks.dmi
  modular_skyrat/modules/gunpoint/code/datum/gunpoint/gunpoint.dm
  modular_skyrat/modules/gunpoint/code/datum/gunpoint/gunpoint_datum.dm
  modular_skyrat/modules/gunpoint/code/datum/gunpoint/gunpoint_radial.dm
  modular_skyrat/modules/gunpoint/icons/radial_gunpoint.dmi
  modular_skyrat/modules/gunpoint/icons/targeted.dmi
  modular_skyrat/modules/gunpoint/readme.md
  modular_skyrat/modules/gunpoint/sound/targetoff.ogg
  modular_skyrat/modules/gunpoint/sound/targeton.ogg
  modular_skyrat/modules/typing_indicator/code/mob.dm
  modular_skyrat/modules/typing_indicator/icons/typing_indicator.dmi
  modular_skyrat/modules/typing_indicator/readme.md
  tgstation.dme
Labels: Feature, Fix me, Test Merged

#212 Command Vendor
  ModularTegustation/tegu_locker_overwrites.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/vending/security.dm
  icons/obj/vending.dmi
Labels: Feature, Map Things, Speedmerge, Tweak

#207 very small Remora fixes
  _maps/map_files/RemoraStation/RemoraStation.dmm
  icons/obj/atmospherics/components/hypertorus.dmi
Labels: Fix, Map Things, Speedmerge

#213 fixes robotics in Chimera.
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
Labels: Fix, Gives GBP, Map Things, Speedmerge
