Repository Quasar-13/Quasar-13, pull requests merged in 2021-03, with the labels that each got.

#3 Adds a structure capsule, an item able to "summon" defined small maps…
  ModularBungalow/cargopacks/goodies.dm
  ModularBungalow/structurescapsules/beacons.dm
  ModularBungalow/structurescapsules/capsules.dm
  ModularBungalow/structurescapsules/structures.dm
  _maps/templates/purplebath.dmm
Labels: Feature, Speedmerge

#4 updates da map
  _maps/map_files/PackedStation/PackedStation.dmm
Labels: Fix, Map Things

#10 pleases the linter gods so checkmarks can now apear by prs
  ModularBungalow/cargopacks/goodies.dm
  ModularBungalow/structurescapsules/capsules.dm
  ModularBungalow/structurescapsules/structures.dm
  ModularBungalow/tableflip.dm
  ModularTegustation/tegu_captainsabre.dm
  ModularTegustation/tegu_weapons/tegumelee.dm
  _maps/templates/purplebath.dmm
  code/__DEFINES/food.dm
Labels: Fix, Speedmerge

#12 Added Extra mutation toxin
  ModularBungalow/bungalowchemistry/bungalowmutation.dm
  tgstation.dme
Labels: Feature

#2 TEG ruin
  ModularTegustation/tegu_ruins/tegruin.dmm
  ModularTegustation/tegu_spaceruins.dm
Labels: Feature, Jones PR, Map Things

#13 Misc Additions 2 (Customs, Workplace Capsules, Cargo goods)
  ModularBungalow/bungalowWeapons/energy.dm
  ModularBungalow/bungalowWeapons/melee.dm
  ModularBungalow/bungalowWeapons/shotguns.dm
  ModularBungalow/cargopacks/goodies.dm
  ModularBungalow/cargopacks/packs.dm
  ModularBungalow/structurescapsules/beacons.dm
  ModularBungalow/structurescapsules/capsules.dm
  ModularBungalow/structurescapsules/structures.dm
  ModularBungalow/zbungalowicons/clothing/back/shotguns.dmi
  ModularBungalow/zbungalowicons/weapons/energy.dmi
  ModularBungalow/zbungalowicons/weapons/energy_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/energy_righthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee.dmi
  ModularBungalow/zbungalowicons/weapons/melee_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee_righthand.dmi
  ModularBungalow/zbungalowicons/weapons/shotguns.dmi
  ModularBungalow/zbungalowicons/weapons/shotguns_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/shotguns_righthand.dmi
  _maps/templates/shelter_purplebath.dmm
  _maps/templates/workplace_chemistry.dmm
  _maps/templates/workplace_hydroponics.dmm
  _maps/templates/workplace_medbay.dmm
Labels: Feature, Fix me, Map Things, Speedmerge

#19 Take a wild fucking guess
  ModularBungalow/zbungalowsounds/felinid/sound_voice_catpeople_nyaha.ogg
  ModularBungalow/zbungalowsounds/felinid/sound_voice_catpeople_nyahaha1.ogg
  ModularBungalow/zbungalowsounds/felinid/sound_voice_catpeople_nyahaha2.ogg
  ModularBungalow/zbungalowsounds/felinid/sound_voice_catpeople_nyahehe.ogg
  code/modules/mob/living/emote.dm
Labels: Affront to God, DO NOT MERGE, Speedmerge

#18 Secretary but good
  ModularBungalow/structurescapsules/capsules.dm
  ModularBungalow/structurescapsules/structures.dm
  ModularTegustation/Teguicons/kirie_stuff/kirieweapons.dmi
  ModularTegustation/Teguicons/kirie_stuff/voidtech.dmi
  ModularTegustation/tegu_global_vars.dm
  ModularTegustation/tegu_jobs/secretary/secretary.dm
  ModularTegustation/tegu_weapons/tegumelee.dm
  _maps/map_files/generic/CentCom.dmm
  _maps/templates/workplace_command.dmm
  code/__DEFINES/jobs.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/jobs/jobs.dm
  tgstation.dme
Labels: Feature, Fix, Map Things

#20 alcoholism is fun
  ModularBungalow/Drinks/Bottles.dm
  ModularBungalow/Drinks/DrinksRecipe.dm
  ModularBungalow/Drinks/drinkscode.dm
  ModularBungalow/Drinks/drinksrecipecrafting.dm
  ModularBungalow/Drinks/vendingmachinecode.dm
  icons/obj/drinks.dmi
Labels: Feature, Speedmerge

#21 Fix alcoholism is fun
  tgstation.dme
Labels: Fix

#1 Added Packedstation for testmerging
  ModularTegustation/tegushuttles.dm
  _maps/_basemap.dm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/packedstation.json
  _maps/shuttles/arrival_packed.dmm
  _maps/shuttles/emergency_packed.dmm
  config/maps.txt
  tgstation.dme
Labels: Map Things

#27 updates packed
  _maps/map_files/PackedStation/PackedStation.dmm
Labels: Fix, Speedmerge

#26 More food!
  ModularBungalow/Drinks/drinksrecipecrafting.dm
  ModularBungalow/Drinks/vendingmachinecode.dm
  ModularBungalow/Drinks_and_food/bottles_code.dm
  ModularBungalow/Drinks_and_food/drinks_chemical_reactiong.dm
  ModularBungalow/Drinks_and_food/drinks_code.dm
  ModularBungalow/Drinks_and_food/drinks_food_Crafting_menu.dm
  ModularBungalow/Drinks_and_food/food_code.dm
  ModularBungalow/Drinks_and_food/icon/food.dmi
  ModularBungalow/Drinks_and_food/vending_machine_code.dm
  icons/obj/drinks.dmi
  tgstation.dme
Labels: Feature, Speedmerge

#23 adds looc
  ModularBungalow/looc.dm
  tgstation.dme
Labels: Feature, Jones PR, Test Merged

#30 Captain weapon rebalance
  ModularBungalow/bungalowWeapons/revolver.dm
  ModularBungalow/zbungalowicons/kirie_stuff/kiriepistols.dmi
  ModularTegustation/tegu_captaingun.dm
  tgstation.dme
Labels: Fix, Speedmerge

#32 Cabin capsule and RTG boards and rarity.
  ModularBungalow/structurescapsules/capsules.dm
  ModularBungalow/structurescapsules/structures.dm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/templates/shelter_cabin.dmm
Labels: Feature, Map Things, Speedmerge

#33 Traitor Changes
  code/__DEFINES/antagonists.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/uplink/uplink_devices.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Speedmerge

#34 Adds Centcom Offices
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Feature, Map Things, Speedmerge

#35 Changes the nukie sniper with a laser one
  ModularBungalow/SecuritySpecialist/specialist.dm
  ModularBungalow/bungalowWeapons/energy.dm
  code/modules/projectiles/guns/energy/sniper.dm
  code/modules/ruins/lavalandruin_code/techcult.dm
Labels: Speedmerge, Tweak

#36 Centcom command headset, and others
  ModularBungalow/SecuritySpecialist/specialist.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/access.dm
Labels: Feature, Fix, Speedmerge

#38 Updates the readme
  README.md
Labels: Documentation, Jones PR, Speedmerge

#39 Adds VT office to Packedstation
  ModularBungalow/zbungalowicons/clothing/parade.dmi
  _maps/map_files/PackedStation/PackedStation.dmm
  tgstation.dme
Labels: Map Things, Speedmerge, Tweak

#25 Bluespace construction bag
  ModularBungalow/bsconstructionbag.dm
  code/game/objects/items/storage/bags.dm
  code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Feature, Jones PR

#40 Fixed the fucking map
  ModularBungalow/ruins/interdyne.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Map Things, Speedmerge, Tweak

#45 temporarily removes interdyne
  tgstation.dme
Labels: Fix

#46 Re-adds interdyne
  tgstation.dme
Labels: Fix

#42 Specialist v2
  ModularBungalow/Clothing/suit.dm
  ModularBungalow/SecuritySpecialist/healthsec.dm
  ModularBungalow/SecuritySpecialist/specialist.dm
  ModularBungalow/zbungalowicons/clothing/coat.dmi
  ModularBungalow/zbungalowicons/clothing/coaticon.dmi
  ModularTegustation/tegu_locker_overwrites.dm
  tgstation.dme
Labels: Feature, Speedmerge
