Repository Quasar-13/Quasar-13, pull requests merged in 2022-03, with the labels that each got.

#610 Captain Sabres Part 2
  ModularBungalow/bungalow_Weapons/melee_weapons.dm
  ModularBungalow/bungalow_beacon.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/zbungalowicons/weapons/melee.dmi
  ModularBungalow/zbungalowicons/weapons/melee_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee_righthand.dmi
  code/game/objects/items/melee/misc.dm
  icons/mob/clothing/belt.dmi
Labels: Test Merged, Tweak, Sprites

#640 No more Rockplanet megafauna
  ModularBungalow/Mining/rockplanet.dm
Labels: Speedmerge, Balance

#639 Fire Jacket and Firecoat
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  code/modules/vending/wardrobes.dm
  icons/mob/human.dmi
Labels: Feature, Speedmerge, Sprites

#611 Kiriechem V4 - Tables 1 and 3
  ModularBungalow/medicine/Kiriechem/mixer.dm
  ModularBungalow/medicine/Kiriechem/reagent.dm
  ModularBungalow/medicine/Kiriechem/reagentselector.dm
Labels: Test Merged, Fix, Tweak, Modular

#641 Updating Fermistation part 13 mister bones' wild ride
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things, Speedmerge

#638 Casio V5: Updating service (again)
  _maps/map_files/CasioStation/Casiostation.dmm
Labels: Map Things, Speedmerge

#403 Attempting to put Frost Demonic Miner to Ice Moon Z-Level
  _maps/RandomRuins/IceRuins/icemoon_surface_asteroid.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_miner_cave.dmm
  code/datums/ruins/icemoon.dm
  config/iceruinblacklist.txt
Labels: Feature, Map Things

#636 Removes the "Dizzy" symptom from virology
  code/datums/diseases/advance/symptoms/dizzy.dm
  tgstation.dme
Labels: Removal, Balance, Headcoder Approval

#643 Netta's Labcoats and the RD labcoat
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrites.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/neocoat.dmi
  ModularBungalow/clothing/neocoat.dm
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/neocoatw.dmi
  code/modules/jobs/job_types/research_director.dm
  code/modules/vending/wardrobes.dm
Labels: Feature, Speedmerge, Sprites

#577 TaliStation, Slime warden pet, new job; hobo and my beloved rainbow shirt
  .github/MAPS_AND_AWAY_MISSIONS.md
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrite_gamemode.dm
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  ModularBungalow/clothing/worn/underwearw.dmi
  ModularBungalow/encryption.dm
  ModularBungalow/mobs/bungalow_simple_animals.dm
  ModularBungalow/sign.dm
  ModularBungalow/zbungalowicons/mobs.dmi
  _maps/_basemap.dm
  _maps/map_files/TaliStation/TaliStation.dmm
  _maps/talistation.json
  code/datums/datacore.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/!talistation/brigdoc.dm
  code/modules/jobs/job_types/!talistation/hobo.dm
  code/modules/jobs/job_types/chemresearcher.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/maps.txt
  icons/mob/hud.dmi
  icons/mob/landmarks.dmi
  icons/obj/card.dmi
  icons/obj/pda.dmi
  tgstation.dme
Labels: Feature, Map Things, Headcoder Approval, Host Approval, Annie Disaproval

#646 Fixes bug with Helioside, Rebalances some Kiriechems
  ModularBungalow/medicine/Kiriechem/mixer.dm
  ModularBungalow/medicine/Kiriechem/reagent.dm
Labels: Speedmerge, Fix, Balance

#632 Paps outfit
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/beret.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/beretw.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/underw.dmi
Labels: Sprites

#650 Fire alarm, Intercom, and newscaster directionals
  code/game/machinery/firealarm.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/devices/radio/intercom.dm
Labels: Feature, Speedmerge

#649 makes the nanotrasen meeting area ( i think that is it's name ) be a heart
  _maps/map_files/generic/CentCom.dmm
Labels: Map Things, Speedmerge, Tweak, quality of life

#653 fixes plat angel's helmet flashlight
  ModularBungalow/mobs/megafauna/rockplanet/platinumangel/items.dm
Labels: Speedmerge, Fix, Headcoder Approval

#651 Talistation 1.1v
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things, Speedmerge, Fix

#644 Adds Clockwork Knight to icemoon
  _maps/RandomRuins/IceRuins/icemoon_underground_clockwork.dmm
  code/datums/ruins/icemoon.dm
Labels: Feature, Map Things, Test Merged

#652 [Port] Removes lattices from our walls, adds CI to help find them and prevent them from occurring again
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/CasioStation/Casiostation_old.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Fermistation/Fermistation.dmm
  _maps/map_files/GalaxyStation/Galaxystation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NTBlacksite/NTBlacksite.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  _maps/map_files/TaliStation/TaliStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  tools/ci/check_grep.sh
Labels: Map Things, Fix, Port

#656 Talistation v1.1b
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things, Fix

#658 Nerf/tweak Apostle
  ModularBungalow/mobs/apostle.dm
  ModularBungalow/mobs/apostle_antag.dm
  ModularTegustation/tegu_items/apostle_items.dm
Labels: Tweak

#335 ultra senior titles
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/bungalow_configs_and_stuff/config.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/access.dm
Labels: Feature, Jones PR, stolen

#659 m90 changes (that are objectively better)
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  icons/obj/guns/projectile.dmi
Labels: Tweak, Sprites

#664 Fixes some area problems in PubbyStation
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Things

#630 [PORT] Makes diagonal movement euclidean
  code/__DEFINES/maths.dm
  code/modules/mob/mob_movement.dm
Labels: Test Merged, quality of life

#637 (Maybe) Kills the 2 hour shift limit
  code/controllers/configuration/entries/general.dm
Labels: Jones PR, Removal

#647 Adds Bamboo Sword, Chain of Captaincy. Removes Chain of Command from all maps.
  ModularBungalow/bungalow_Weapons/bamboo.dm
  ModularBungalow/bungalow_Weapons/melee_weapons.dm
  ModularBungalow/bungalow_beacon.dm
  ModularBungalow/zbungalowicons/weapons/melee.dmi
  ModularBungalow/zbungalowicons/weapons/melee_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee_righthand.dmi
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Fermistation/Fermistation.dmm
  _maps/map_files/GalaxyStation/Galaxystation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/TaliStation/TaliStation.dmm
  icons/mob/clothing/belt.dmi
  icons/obj/clothing/belts.dmi
  tgstation.dme
Labels: Feature, Test Merged, Sprites, Annie Disaproval

#634 Ports pixel shifting
  code/__DEFINES/keybinding.dm
  code/datums/keybinding/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/pixel_shift.dm
  tgstation.dme
Labels: Feature, Headcoder Approval, Port, Annie Disaproval, Merge Ready

#666 Minor changes to box, pubby and talistation
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things

#668 fixes burn woundtending with health analyzer saying brute
  code/modules/surgery/healing.dm
Labels: Fix

#674 Resprites the classic laser gun
  ModularBungalow/bungalow_Weapons/_icon/energy.dmi
Labels: Sprites

#675 TaliStation v1.1e?
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things

#645 Mining Overhaul and Asteroid Mining Field
  ModularBungalow/Mining/asteroidbelt.dm
  ModularBungalow/Mining/rockplanet.dm
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_configs_and_stuff/global_list.dm
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/icons/beret.dmi
  ModularBungalow/clothing/worn/beretw.dmi
  ModularBungalow/zbungalowicons/turfs.dmi
  _maps/RandomRuins/AsteroidRuins/asteroid_apostlespear.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_apostlestaff.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_assistant.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_base.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_cult.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_darkbible.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_glockroach.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_hellspawn.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_large.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_lube.dmm
  _maps/RandomRuins/AsteroidRuins/asteroid_moth.dmm
  _maps/map_files/Mining/Asteroidbelt.dmm
  _maps/map_files/Mining/Rockplanet.dmm
  code/__DEFINES/maps.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/mapping.dm
  code/datums/mapgen/JungleGenerator.dm
  code/datums/ruins/asteroid.dm
  code/datums/ruins/rockplanet.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/diamond.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/datums/weather/weather_types/space_wind.dm
  code/datums/weather/weather_types/void_storm.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  config/mining_levels.txt
  icons/effects/weather_effects.dmi
  tgstation.dme
Labels: Feature, Map Things, Balance, Sprites, Merge Ready

#665 New jungle base.
  _maps/map_files/Mining/Jungle.dmm
Labels: Map Things, Test Merged, Headcoder Approval

#676 Talistation 1.2
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things, DO NOT MERGE

#678 Removes Pubby double airlocks and fix a thing in talistation.
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things, Fix

#680 Necromancer/tomb tweaks
  ModularBungalow/mobs/necromancer.dm
  ModularBungalow/mobs/necromancer_skeletons.dm
  code/modules/tomb_worlds/loot.dm
  code/modules/tomb_worlds/spawner.dm
Labels: Fix, Tweak

#673 cult soulstones work on catatonic cultists
  code/modules/antagonists/wizard/equipment/soulstone.dm
Labels: Balance

#683 bugfixes for talistation
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things, Speedmerge, Fix
