Repository Quasar-13/Quasar-13, pull requests merged in 2022-05, with the labels that each got.

#679 Literal Drinks: A TomSka inspired PR
  code/game/atoms_movable.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#726 New Rock Megafauna, Asteroid Belt Station Crew
  ModularBungalow/bungalow_Weapons/Energy/sniper.dm
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/_icon/energy.dmi
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/mobs/megafauna/rockplanet/!modifications/claw.dm
  ModularBungalow/mobs/megafauna/rockplanet/!modifications/hierophant.dm
  ModularBungalow/mobs/megafauna/rockplanet/arlem/megafauna.dm
  ModularBungalow/mobs/megafauna/rockplanet/arlem/mob.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/icons/item_lefthand.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/icons/item_righthand.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/icons/sif.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/icons/worn.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/items.dm
  ModularBungalow/mobs/megafauna/rockplanet/sif/sif.dm
  ModularBungalow/mobs/megafauna/rockplanet/sif/sif.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/sif_sword.dmi
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/blade_spin.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/death_howl.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/howl.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/sif_slash.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/sif_stomp.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/whoosh1.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/whoosh2.ogg
  ModularBungalow/mobs/megafauna/rockplanet/sif/sound/whoosh3.ogg
  ModularBungalow/ruins/spawners.dm
  _maps/RandomRuins/RockRuins/rockplanet_arlem.dmm
  _maps/RandomRuins/RockRuins/rockplanet_claw.dmm
  _maps/RandomRuins/RockRuins/rockplanet_heirophant.dmm
  _maps/RandomRuins/RockRuins/rockplanet_sif.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/Mining/Asteroidbelt.dmm
  code/datums/ruins/asteroid.dm
  code/datums/ruins/jungle.dm
  code/datums/ruins/rockplanet.dm
  code/modules/projectiles/guns/energy/sniper.dm
  tgstation.dme
Labels: Feature, Sprites, Port

#736 Change "ambience" preference
  code/modules/client/preferences_toggles.dm
Labels: Fix, Tweak

#733 [MDB Ignore]Romulus Overhaul
  ModularBungalow/bungalow_Weapons/Energy/sniper.dm
  ModularBungalow/bungalow_Weapons/_icon/ammo_box.dmi
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/ammoboxes.dm
  ModularBungalow/bungalow_Weapons/ammocasing/energy.dm
  ModularBungalow/bungalow_Weapons/ammocasing/pistol.dm
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/bungalow_Weapons/weapontierspawner.dm
  ModularBungalow/mobs/solgov.dm
  ModularBungalow/project_kepler/items.dm
  ModularBungalow/project_kepler/kepler_machinery.dm
  ModularBungalow/project_kepler/kepler_machinery.dmi
  ModularBungalow/project_kepler/militarykits.dm
  ModularTegustation/Teguicons/kirie_stuff/kiriepistols.dmi
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/modules/clothing/under/syndicate.dm
  code/modules/jobs/job_types/!extra/kepler/ice/!outfits.dm
  code/modules/jobs/job_types/!extra/kepler/ice/jobs/solgov.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  tgstation.dme
Labels: Project Kepler

#735 adds GPS and oreboxes to mining maps missing them
  _maps/map_files/Mining/Asteroidbelt.dmm
  _maps/map_files/Mining/Jungle.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/Mining/Rockplanet.dmm
  _maps/map_files/Mining/Tidalmoon.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/TaliStation/TaliStation.dmm
Labels: Map Things

#737 adds blood-drunk miner to rockplanet, readds goliaths and hivelords and changes some other misc stuff
  ModularBungalow/Mining/rockplanet.dm
  ModularBungalow/mobs/megafauna/rockplanet/platinumangel/megafauna.dm
  _maps/RandomRuins/RockRuins/rockplanet_blooddrunk.dmm
  _maps/RandomRuins/RockRuins/rockplanet_platinum.dmm
  _maps/map_files/Mining/Tidalmoon.dmm
  code/datums/ruins/rockplanet.dm
  code/game/objects/items/devices/gps.dm
Labels: Tweak

#715 [PORT] Thrownthing datum refactor: you can now throw stuff at mobs lying on the floor.
  code/__DEFINES/keybinding.dm
  code/__DEFINES/mobs.dm
  code/_onclick/click.dm
  code/controllers/subsystem/throwing.dm
  code/datums/components/tackle.dm
  code/datums/keybinding/carbon.dm
  code/datums/martial/sleeping_carp.dm
  code/datums/mutations/hulk.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/objects/effects/mines.dm
  code/game/objects/items/stunbaton.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/client/preferences_savefile.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_defines.dm
  code/modules/ninja/suit/ninja_equipment_actions/ninja_stars.dm
  code/modules/paperwork/paperplane.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/surgery/organs/vocal_cords.dm
Labels: Fix, Balance

#732 New Atmos hardsuit
  ModularBungalow/clothing/hardsuits.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/head.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/headw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#744 makes gravity gen be shut
  code/datums/looping_sounds/machinery_sounds.dm
Labels: Speedmerge, GLORY TO GOD IN THE HIGHEST

#741 New Marine Hardsuits (and some unatomized map fixes)
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Sprites

#631 ports TG's HF blade
  code/__DEFINES/antagonists.dm
  code/__HELPERS/matrices.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/photography/camera/camera_image_capturing.dm
  icons/effects/effects.dmi
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt_mirror.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature, Port

#749 Kepler Hotfix
  code/modules/jobs/jobs.dm
Labels: Speedmerge, Fix

#743 New EMAG Sprites
  code/game/objects/items/emags.dm
  icons/obj/card.dmi
Labels: Sprites

#692 Punishing bird
  code/modules/mob/living/simple_animal/hostile/retaliate/punishing_bird.dm
  icons/mob/punishing_bird.dmi
  sound/weapons/pbird_bite.ogg
  tgstation.dme
Labels: Feature

#755 Multiple Gun and Misc Fixes
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  ModularBungalow/clothing/wintercoats.dm
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Sprites

#756 Fermistation v15 epic hotfix
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Fix

#757 Casiostation Armory Improvement
  _maps/map_files/CasioStation/Casiostation.dmm
  code/modules/projectiles/guns/energy/energy_gun.dm
Labels: Map Things, Tweak
