Repository Quasar-13/Quasar-13, pull requests merged in 2022-12, with the labels that each got.

#797 Ports nanite heart from yogstation
  code/modules/research/designs/medical_designs.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/heart.dm
Labels: Port

#754 An Ided Cybersunship Buff
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Tweak

#687 [PORT] Mild Blood Rites QoL and Blood Halberd cleanup + sprites
  code/__DEFINES/cult.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  icons/mob/actions/actions_cult.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites, Quality of Life, Port

#775 Icemoon V3
  _maps/map_files/Mining/Icemoon.dmm
  code/datums/mapgen/Cavegens/IcemoonCaves.dm
Labels: Feature, Map Things, Tweak

#633 [TG PORT] Adds some new (proper) tables. Also fixes the old reinforced glass table just making a regular metal table bug for the alloys included.
  ModularBungalow/tableflip.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/tables_racks.dm
  icons/obj/smooth_structures/plastitaniumglass_table.dmi
  icons/obj/smooth_structures/rglass_table.dmi
  icons/obj/smooth_structures/rplasmaglass_table.dmi
  icons/obj/smooth_structures/titaniumglass_table.dmi
Labels: Feature, Sprites, Port

#802 syndicate gasmasks nolonger burnup
  code/modules/clothing/masks/gasmask.dm
Labels: Speedmerge, Balance
