Repository Quasar-13/Quasar-13, pull requests merged in 2022-04, with the labels that each got.

#690 Maids for april fools
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/under/civilian.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/under/civilian.dmi
Labels: Affront to God, Sprites, quality of life, Port, Merge Ready

#694 HOP Clothing name fix
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/under.dm
Labels: Speedmerge, Fix

#693 Kepler Major Update 1
  ModularBungalow/bungalow_Weapons/ballistic/carbines.dm
  ModularBungalow/bungalow_Weapons/ballistic/smgs.dm
  ModularBungalow/bungalow_areas.dm
  ModularBungalow/clothing/headset.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/!terragov/administrator.dm
  code/modules/jobs/job_types/!terragov/bunker_crew.dm
  code/modules/jobs/job_types/!terragov/commander.dm
  code/modules/jobs/job_types/!terragov/engineer.dm
  code/modules/jobs/job_types/!terragov/outpost/agent.dm
  code/modules/jobs/job_types/!terragov/sneedclave/remlieutenant.dm
  code/modules/jobs/job_types/!terragov/sneedclave/remprivate.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Map Things, Merge Ready

#695 Tidalmoon Update
  _maps/map_files/Mining/Tidalmoon.dmm
Labels: Map Things, Fix

#697 Fallout 13-Style Shotgun Ammo, The VECTOR and Two future Sec pistols
  ModularBungalow/bungalow_Weapons/_icon/ammo_box.dmi
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/_icon/leveraction.dmi
  ModularBungalow/bungalow_Weapons/_icon/shotgunshell.dmi
  ModularBungalow/bungalow_Weapons/ammoboxes.dm
  ModularBungalow/bungalow_Weapons/ammocasing/ShotgunShells.dm
  ModularBungalow/bungalow_Weapons/ammocasing/rubbers.dm
  ModularBungalow/bungalow_Weapons/ballistic/leveraction.dm
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  ModularBungalow/bungalow_Weapons/ballistic/shotgun.dm
  ModularBungalow/bungalow_Weapons/ballistic/smgs.dm
  ModularBungalow/bungalow_Weapons/gunsmithing/recipes.dm
  ModularBungalow/cargo/goodies.dm
  ModularBungalow/cargo/guncrafting.dm
  ModularBungalow/cargo/packs.dm
  ModularBungalow/clothing/storage.dm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/AndromedaStation/Andromeda.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Fermistation/Fermistation.dmm
  _maps/map_files/GalaxyStation/Galaxystation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NTBlacksite/NTBlacksite.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  _maps/map_files/RemusFacility/RemusFacility.dmm
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  _maps/map_files/TaliStation/TaliStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/pirate_default.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/antagonists/gang/outfits.dm
  code/modules/cargo/packs.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/vending/wardrobes.dm
  icons/mob/inhands/weapons/64x_guns_left.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Map Things, Balance, Sprites, quality of life, Annie Disaproval

#699 Kepler Update Part 2 (Romulus Facility)
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  icons/mob/clothing/belt.dmi
Labels: Map Things

#669 [PORT] Geyser rebalancing, gives miners points for discovering geysers
  code/datums/mapgen/Cavegens/IcemoonCaves.dm
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/game/objects/structures/lavaland/geyser.dm
  code/modules/vending/medical.dm
Labels: Feature, Balance, Headmin Approval, Test Merge Candidate

#703 Adds chem lab to Romulus
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
Labels: Map Things, Speedmerge

#704 De-shittifies packed mining
  ModularBungalow/clothing/headset.dm
  _maps/map_files/Mining/Asteroidbelt.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/modules/jobs/job_types/!packed/commsofficer.dm
  code/modules/jobs/job_types/!packed/gooncargo.dm
Labels: Map Things, Speedmerge, Fix, Tweak

#702 Fermistation v14 probably the last part 2
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things, Fix

#706 Kepler Update Part 3
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
Labels: Map Things

#700 Changing L504
  ModularBungalow/bungalow_Weapons/Energy/rifle.dm
  ModularBungalow/bungalow_Weapons/_icon/energy.dmi
Labels: Sprites

#708 thicc 1911
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Sprites

#709 SMC Armor
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/smc.dm
  ModularBungalow/clothing/worn/coatw.dmi
  code/modules/jobs/job_types/!syndicate/marine.dm
Labels: Sprites, Port

#698 Automatic Bulldog
  ModularBungalow/bungalow_Weapons/ballistic/shotgun.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#686 Anarchy doesn't delete equipment
  code/modules/admin/verbs/secrets.dm
Labels: Tweak

#711 Fix claw attacks
  ModularBungalow/mobs/the_claw.dm
Labels: Fix, Tweak, Headcoder Approval

#714 fixes geysers not being plunged
  code/game/objects/structures/lavaland/geyser.dm
  code/modules/clothing/head/misc.dm
Labels: Fix

#707 Kepler Map Update Part 3.5B. Huge Content!
  ModularBungalow/bungalow_Weapons/_icon/ammo_box.dmi
  ModularBungalow/bungalow_Weapons/ammoboxes.dm
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/icons/beret.dmi
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/beretw.dmi
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  ModularBungalow/jonescanner.dm
  ModularTegustation/Teguicons/goldens_treasures/cloaks.dmi
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/solgov.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/mob/clothing/under/misc.dmi
  icons/mob/clothing/under/security.dmi
  icons/mob/clothing/under/syndicate.dmi
  icons/mob/icemoon/icemoon_monsters.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/simple_human.dmi
  icons/obj/clothing/under/misc.dmi
  icons/obj/clothing/under/security.dmi
  icons/obj/clothing/under/syndicate.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Map Things

#712 Minor Uniform Related Improvements
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/parade.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/jobs/job_types/!casio/blueshield.dm
  code/modules/jobs/job_types/!packed/commsofficer.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/research_director.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Tweak, Sprites

#716 Blacksite Update
  ModularBungalow/SecuritySpecialist/mechpilot.dm
  ModularBungalow/bungalow_Weapons/ammoboxes.dm
  ModularBungalow/bungalow_Weapons/ammocasing/rifle.dm
  ModularBungalow/bungalow_Weapons/ammocasing/rocket.dm
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/bungalow_Weapons/energymelee.dm
  ModularBungalow/bungalow_beacon.dm
  ModularBungalow/cargo/goodies.dm
  ModularBungalow/cargo/packs.dm
  ModularBungalow/clothing/ntblacksite.dm
  ModularBungalow/clothing/storage.dm
  ModularBungalow/structurescapsules/beacons.dm
  _maps/RandomRuins/admin/drekar.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/modules/jobs/job_types/!blacksite/deathsquad.dm
  code/modules/jobs/job_types/!blacksite/ertcommander.dm
  code/modules/jobs/job_types/!blacksite/ertengineer.dm
  code/modules/jobs/job_types/!blacksite/ertmedic.dm
  code/modules/jobs/job_types/!blacksite/ertsecurity.dm
  code/modules/jobs/job_types/!blacksite/ntoperator.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  tgstation.dme
Labels: Speedmerge, Fix

#713 Port Ambience Refactor
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/ambience.dm
  code/game/area/areas.dm
  code/game/area/areas/mining.dm
  code/game/area/space_station_13_areas.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences_toggles.dm
  html/changelogs/KALESONKI-713-PR.yml
  tgstation.dme
Labels: Port, Host Approval, Test Merge Candidate

#719 smc vest fix
  ModularBungalow/clothing/worn/coatw.dmi
Labels: Speedmerge, Fix, Sprites

#717 kepler station update v4
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/icons/mask.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/mask.dm
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  ModularBungalow/clothing/worn/maskw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  ModularBungalow/mobs/solgov.dm
  ModularBungalow/sign.dm
  ModularBungalow/zbungalowicons/decal.dmi
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/__DEFINES/projectiles.dm
  code/modules/mob/living/simple_animal/hostile/solgov.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/caseless/rocket.dm
  code/modules/projectiles/boxes_magazines/external/grenade.dm
  code/modules/projectiles/boxes_magazines/internal/grenade.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets/grenade.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/simple_human.dmi
  icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Feature, Speedmerge, Sprites, Project Kepler

#721 Fixes path regarding helmets (and unatomized weapon nerf)
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/clothing/helmet.dm
Labels: Speedmerge, Fix

#722 kepler station updoot v5 (722)
  ModularBungalow/bungalow_Weapons/_icon/ammo_box.dmi
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/ammoboxes.dm
  ModularBungalow/bungalow_Weapons/ballistic/leveraction.dm
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/bungalow_Weapons/ballistic/shotgun.dm
  ModularBungalow/bungalow_Weapons/ballistic/smgs.dm
  ModularBungalow/bungalow_Weapons/melee_weapons.dm
  ModularBungalow/bungalow_Weapons/weapontierspawner.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/mask.dmi
  ModularBungalow/clothing/mask.dm
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/maskw.dmi
  ModularBungalow/mobs/infectedspawner.dm
  ModularBungalow/mobs/solgov.dm
  ModularBungalow/zbungalowicons/decal.dmi
  ModularBungalow/zbungalowicons/weapons/shotguns_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/shotguns_righthand.dmi
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/mob/animal.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/simple_human.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/syringe.dmi
  tgstation.dme
Labels: Project Kepler

#720 Revamping the Surplus Rifle
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/obj/guns/projectile.dmi
Labels: Feature, Sprites
