Repository Quasar-13/Quasar-13, pull requests merged in 2022-02, with the labels that each got.

#471 Atmos enhanced. Part 1: Crystallizer and machine recipes [PORT OF TG #56889]
  code/datums/components/crafting/recipes.dm
  code/datums/materials/basemats.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/fireaxe.dm
  code/game/objects/items/grenades/atmos_grenades.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/components/gas_recipe_machines/crystallizer_items.dm
  code/modules/atmospherics/machinery/components/machines/atmos_machines_recipes.dm
  code/modules/atmospherics/machinery/components/machines/crystallizer.dm
  code/modules/power/cell.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/inhands/misc/sheets_lefthand.dmi
  icons/mob/inhands/misc/sheets_righthand.dmi
  icons/mob/inhands/weapons/axes_lefthand.dmi
  icons/mob/inhands/weapons/axes_righthand.dmi
  icons/obj/atmospherics/components/machines.dmi
  icons/obj/grenade.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/power.dmi
  icons/obj/stack_objects.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/Crystallizer.js
Labels: Feature

#538 BNI Agent Hardsuit
  ModularBungalow/clothing/hardsuits.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  tgstation.dme
Labels: Fix me, Feature, quality of life

#516 Borg hardstun nerf
  code/game/objects/items/robot/robot_items.dm
Labels: Affront to God, Speedmerge, Balance

#539 gives necromancer a icon in achievements
  code/modules/asset_cache/asset_list_items.dm
  icons/UI_Icons/Achievements/Boss/necromancer.png
Labels: Tweak, Sprites

#536 Casiostation v4: Reservicing
  _maps/map_files/CasioStation/Casiostation.dmm
Labels: Map Things

#544 Updating Fermistation part 8 Engineering rework
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things, Fix

#540 Big spoon
  ModularBungalow/spoon/spoon.dm
  ModularBungalow/spoon/spoon_icon/64icons.dmi
  ModularBungalow/spoon/spoon_icon/icons.dmi
  ModularBungalow/spoon/spoon_icon/lefthand.dmi
  ModularBungalow/spoon/spoon_icon/righthand.dmi
  tgstation.dme
Labels: Feature, Sprites

#542 adds balloon alerts from TG
  code/__DEFINES/layers.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/text.dm
  code/__HELPERS/game.dm
  code/datums/chatmessage.dm
  code/modules/balloon_alert/balloon_alert.dm
  code/modules/reagents/reagent_containers.dm
  tgstation.dme
Labels: Feature, Test Merged, quality of life

#545 Mechanic Ship upgrade and Casio fixes
  _maps/RandomRuins/SpaceRuins/asteroid5.dmm
  _maps/RandomRuins/SpaceRuins/derelict5.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/shuttles/building_mechanic.dmm
Labels: Map Things

#546 No more gibbing the admirals
  ModularBungalow/clothing/parade.dm
Labels: Speedmerge, Balance

#548 Adds in ANOTHER meeting room and unatomized Remora changes
  ModularBungalow/clothing/accessory.dm
  ModularBungalow/clothing/worn/paradew.dmi
  _maps/map_files/RemoraStation/RemoraStation.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Map Things, Fix

#547 adds slowclapz
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  sound/machines/slowclap.ogg
Labels: Feature

#549 Some packed station runtime fixes and other things.
  _maps/map_files/PackedStation/PackedStation.dmm
Labels: Map Things, Fix

#550 Mk23change
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
Labels: Balance, Lore

#541 Status Module functions for Discord Bot
  code/controllers/configuration/entries/comms.dm
  code/controllers/subsystem/redbot.dm
  code/datums/world_topic.dm
  code/modules/admin/sql_ban_system.dm
  tgstation.dme
Labels: Test Merged, Needs Headcoder Approval, admin

#520 Framework for New Antagonist: BNI Black Ops Agent & NT-Exclusive Uplink
  ModularBungalow/bungalow_Weapons/Energy/rifle.dm
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/names.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/ntblackops/nt_blackops.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/secure.dm
  code/modules/antagonists/nt_blackops/nt_blackops.dm
  code/modules/antagonists/nt_blackops/nt_extraction_kit.dm
  code/modules/antagonists/nt_blackops/nt_uplink_items.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/uplink/uplink_devices.dm
  code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Fix me, Feature, Lore

#557 Ports mobs from skyrat
  code/__DEFINES/traits.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/hydroponics/grown/bananaspider.dm
  code/modules/mob/living/simple_animal/friendly/bananaspider.dm
  code/modules/mob/living/simple_animal/friendly/kiwi.dm
  code/modules/mob/living/simple_animal/hostile/grabbagmob.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/vending/megaseed.dm
  icons/mob/newmobs.dmi
  icons/mob/newmobs32x64.dmi
  icons/mob/newmobs64x32.dmi
  icons/mob/newmobs64x64.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Feature, Speedmerge

#558 Revert "Ports mobs from skyrat"
  code/__DEFINES/traits.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/hydroponics/grown/bananaspider.dm
  code/modules/mob/living/simple_animal/friendly/bananaspider.dm
  code/modules/mob/living/simple_animal/friendly/kiwi.dm
  code/modules/mob/living/simple_animal/hostile/grabbagmob.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/vending/megaseed.dm
  icons/mob/newmobs.dmi
  icons/mob/newmobs32x64.dmi
  icons/mob/newmobs64x32.dmi
  icons/mob/newmobs64x64.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Speedmerge, Fix, Gives GBP, Removal

#559 Adds glass gas mask from skyrat
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/clothing/masks/breath.dm
  icons/mob/clothing/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, Sprites, Port

#563 Debug Glasses!
  code/modules/clothing/glasses/_glasses.dm
Labels: Tweak, Xan seal of approval (not trademarked), admin, quality of life

#560 stupid simple fix
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
Labels: Fix, Tweak, quality of life, Port

#561 Alot of minor casio station fixes
  _maps/map_files/CasioStation/Casiostation.dmm
Labels: Map Things, Fix, quality of life

#565 Gives medics maint access on lowpop
  code/modules/jobs/job_types/medical_doctor.dm
Labels: Tweak, Balance, quality of life

#522 Romulus Facility
  ModularBungalow/sign.dm
  ModularBungalow/zbungalowicons/decal.dmi
  _maps/_basemap.dm
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  _maps/romulusfacility.json
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/datums/datacore.dm
  code/modules/jobs/job_types/!blacksite/bridge.dm
  code/modules/jobs/job_types/!blacksite/ntmedical.dm
  code/modules/jobs/job_types/!casio/blueshield.dm
  code/modules/jobs/job_types/!terragov/administrator.dm
  code/modules/jobs/job_types/!terragov/bunker_crew.dm
  code/modules/jobs/job_types/!terragov/civilian.dm
  code/modules/jobs/job_types/!terragov/commander.dm
  code/modules/jobs/job_types/!terragov/engineer.dm
  code/modules/jobs/job_types/!terragov/lab_technician.dm
  code/modules/jobs/job_types/!terragov/medical_technician.dm
  code/modules/jobs/job_types/!terragov/outpost/agent.dm
  code/modules/jobs/job_types/!terragov/outpost/explorer.dm
  code/modules/jobs/job_types/!terragov/outpost/leader.dm
  code/modules/jobs/job_types/!terragov/outpost/medic.dm
  code/modules/jobs/job_types/!terragov/outpost/scientist.dm
  code/modules/jobs/job_types/!terragov/security.dm
  code/modules/jobs/job_types/!terragov/sneedclave/remaux.dm
  code/modules/jobs/job_types/!terragov/sneedclave/remlieutenant.dm
  code/modules/jobs/job_types/!terragov/sneedclave/remprivate.dm
  code/modules/jobs/job_types/!terragov/soldier.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/secretary.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/ice whelp.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/lobstrosity.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
  config/maps.txt
  icons/mob/hud.dmi
  tgstation.dme
Labels: Feature, Map Things, Test Merged

#568 Xeno weed cahnges [PORT]
  code/game/objects/structures/aliens.dm
Labels: Tweak, Balance, Port

#566 Xeno nerfs (Again)
  code/modules/jobs/job_types/!packed/gooncargo.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid_defense.dm
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Balance

#567 Warden Resprite
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#564 Revert "Revert "Ports mobs from skyrat""
  code/__DEFINES/traits.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/hydroponics/grown/bananaspider.dm
  code/modules/mob/living/simple_animal/friendly/bananaspider.dm
  code/modules/mob/living/simple_animal/friendly/kiwi.dm
  code/modules/mob/living/simple_animal/hostile/grabbagmob.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/vending/megaseed.dm
  icons/mob/newmobs.dmi
  icons/mob/newmobs32x64.dmi
  icons/mob/newmobs64x64.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Feature

#570 Changing the Bacchus' Blessing Sprite to be Better
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Fix, Tweak, Sprites, quality of life

#574 Updating Fermistation part 10 i take this brick and i place it next to this brick
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things

#576 Spacepol and Welding gas mask fixes.
  icons/mob/clothing/mask.dmi
Labels: Speedmerge, Fix, Sprites

#562 The Wallening Approacheth: Adds directional variants to most wall mounts [PORT]
  code/game/machinery/bounty_board.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/machinery/flasher.dm
  code/game/machinery/igniter.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/fireaxe.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/noticeboard.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mining/aux_base.dm
  code/modules/paperwork/ticketmachine.dm
  code/modules/power/lighting.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/vending/medical_wall.dm
Labels: Feature, Port

#573 Xans outfit
  ModularBungalow/bungalow_Weapons/melee_weapons.dm
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/gloves.dm
  ModularBungalow/clothing/icons/beret.dmi
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/gloves.dmi
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/beretw.dmi
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/glovesw.dmi
  ModularBungalow/clothing/worn/paradew.dmi
  ModularBungalow/clothing/worn/underw.dmi
  ModularBungalow/zbungalowicons/effects.dmi
  ModularBungalow/zbungalowicons/weapons/Meleew.dmi
  ModularBungalow/zbungalowicons/weapons/melee.dmi
  ModularBungalow/zbungalowicons/weapons/melee_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee_righthand.dmi
  tgstation.dme
Labels: Feature, Sprites

#579 357 Casings
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  icons/obj/ammo.dmi
Labels: Sprites, quality of life

#580 Adds NT and Syndicate bases to Remus 2, very messily
  _maps/map_files/RemusFacility/RemusFacility.dmm
  code/datums/mapgen/biomes/_biome.dm
  code/modules/jobs/job_types/!terragov/outpost/scientist.dm
Labels: Map Things

#578 Swat Helmet Update
  code/modules/clothing/head/helmet.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#581 Minor Fixes of Many(spriting) Kinds
  code/modules/clothing/suits/armor.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/under/centcom.dmi
  icons/mob/clothing/under/security.dmi
  icons/obj/clothing/suits.dmi
Labels: Fix, Sprites

#586 Armor Changes
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#587 Updating Fermistation part 11 maint fixes
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Affront to God, Xan seal of approval (not trademarked)

#588 navy captain fix
  code/modules/jobs/job_types/!casio/ntcaptain.dm
Labels: quality of life

#589 BNI Outfits
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/icons/beret.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/beretw.dmi
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/jobs.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#592 BNI Intelligence Officer
  ModularBungalow/altjobtitles/outfits.dm
Labels: Lore

#553 Polishing ban notice
  code/modules/admin/sql_ban_system.dm
Labels: Kirie Seal Of Approval (trademarked), admin

#594 Minor Sec Stat Change
  _maps/map_files/Fermistation/Fermistation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
Labels: Tweak, Balance

#596 The mega port (Resprites, Admin things, QoL and other stuff)
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/power/lighting.dm
  code/modules/station_goals/bsa.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
Labels: Feature, Fix, Gives GBP, Sprites, Kirie Seal Of Approval (trademarked), quality of life, Port

#595 [PORT] security uniform resprites
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/under/security.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/under/security.dmi
Labels: Sprites, Port

#593 Nuke extools
  SpacemanDMM.toml
  code/__DEFINES/_tick.dm
  code/__DEFINES/qdel.dm
  code/__DEFINES/spaceman_dmm.dm
  code/__DEFINES/vv.dm
  code/_compile_options.dm
  code/controllers/subsystem/garbage.dm
  code/datums/datumvars.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/view_variables.dm
Labels: Test Merged, Affront to God, Fix, Gives GBP, admin

#597 Removes Health Analyzers
  ModularBungalow/xenoarch/xenoarch_reward.dm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/Fermistation/Fermistation.dmm
  _maps/map_files/GalaxyStation/Galaxystation.dmm
  _maps/map_files/GalaxyStation/Galaxystation_LVL2.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/modules/vending/medical_wall.dm
  code/modules/vending/robotics.dm
Labels: Speedmerge, Balance

#599 New Contraband for Cargo Wardrobe
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/under/misc.dmi
  icons/obj/clothing/under/misc.dmi
Labels: Tweak, Sprites

#598 Adds Black Beret to Sec vendor
  ModularBungalow/vending_machine_edits.dm
Labels: Speedmerge, Tweak

#479 Ports exploration drones from tg! [PORT FROM TG]
  _maps/map_files/GalaxyStation/Galaxystation_LVL2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/adventure.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/persistence.dm
  code/datums/components/twohanded.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/credit_holochip.dm
  code/game/objects/items/pet_carrier.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/atmospherics/machinery/components/machines/atmos_machines_recipes.dm
  code/modules/cargo/exports/antiques.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/explorer_drone/adventure.dm
  code/modules/explorer_drone/control_console.dm
  code/modules/explorer_drone/exodrone.dm
  code/modules/explorer_drone/exploration_events/_exploration_event.dm
  code/modules/explorer_drone/exploration_events/adventure.dm
  code/modules/explorer_drone/exploration_events/danger.dm
  code/modules/explorer_drone/exploration_events/exploration_site.dm
  code/modules/explorer_drone/exploration_events/fluff.dm
  code/modules/explorer_drone/exploration_events/resource.dm
  code/modules/explorer_drone/exploration_events/trader.dm
  code/modules/explorer_drone/loot.dm
  code/modules/explorer_drone/scanner_array.dm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/xenobiology/vatgrowing/petri_dish.dm
  config/adventures/SYNDIKILLER2000.json
  config/adventures/Theres_a_tree_in_the_middle_of_space.json
  config/adventures/a_model_earth.json
  icons/UI_Icons/adventure/default.png
  icons/UI_Icons/adventure/grue.png
  icons/UI_Icons/adventure/signal_lost.png
  icons/UI_Icons/adventure/trade.png
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/id_card.dmi
  icons/mob/inhands/firelance_lefthand.dmi
  icons/mob/inhands/firelance_righthand.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/misc/firelance_lefthand.dmi
  icons/mob/inhands/misc/firelance_righthand.dmi
  icons/obj/bio.dmi
  icons/obj/card.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/exploration.dmi
  icons/obj/pet_carrier.dmi
  strings/exodrone.json
  tgstation.dme
  tgui/packages/tgui/components/TimeDisplay.js
  tgui/packages/tgui/format.js
  tgui/packages/tgui/interfaces/ExodroneConsole.tsx
  tgui/packages/tgui/interfaces/ExoscannerConsole.tsx
Labels: Feature, Port

#450 Ports slings from yog
  ModularBungalow/zbungalowicons/clothing/suit.dmi
  ModularBungalow/zbungalowicons/mob/suits.dmi
  code/__DEFINES/antagonists.dm
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/role_preferences.dm
  code/datums/components/walk.dm
  code/datums/mind.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/quirks/negative.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/antagonists/shadowling/ascendant_shadowling.dm
  code/modules/antagonists/shadowling/shadowling.dm
  code/modules/antagonists/shadowling/shadowling_abilities.dm
  code/modules/antagonists/shadowling/shadowling_items.dm
  code/modules/antagonists/shadowling/special_shadowling_abilities.dm
  code/modules/antagonists/shadowling/thrall.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
  code/modules/reagents/chemistry/other_reagents.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/organs/shadowling_organs.dm
  icons/effects/cult_target.dmi
  icons/mob/actions.dmi
  icons/mob/hud.dmi
  icons/mob/mutant_bodyparts.dmi
  icons/mob/sling.dmi
  sound/ambience/antag/sling.ogg
  sound/ambience/antag/thrall.ogg
  tgstation.dme
Labels: Feature, Kirie Seal Of Approval (trademarked), Port

#600 Geneticist, New
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
Labels: Affront to God, Tweak

#604 Protected Custody
  ModularBungalow/altjobtitles/alt_titles.dm
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/underw.dmi
Labels: Feature, Sprites, Modular

#606 Drip Again - Atmospherics and Command Drip Finalized
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrites.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  _maps/map_files/PackedStation/PackedStation.dmm
  code/modules/vending/security.dm
  code/modules/vending/wardrobes.dm
Labels: Map Things, Tweak, Sprites

#605 CC Commander update
  code/modules/clothing/outfits/standard.dm
Labels: Tweak

#607 Provost and VADM accessories
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/gloves.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/gloves.dmi
  ModularBungalow/clothing/icons/head.dmi
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/glovesw.dmi
  ModularBungalow/clothing/worn/headw.dmi
  ModularBungalow/clothing/worn/paradew.dmi
  code/modules/clothing/outfits/standard.dm
Labels: Speedmerge, Sprites

#609 QM drip
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrites.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  _maps/map_files/PackedStation/PackedStation.dmm
  code/modules/jobs/job_types/!packed/commsofficer.dm
Labels: Sprites

#608 Card ID updates
  code/game/objects/items/cards_ids.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Tweak, Sprites

#612 The QM's ranger Duster
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Things, Speedmerge, Tweak

#613 Fixes lawyer's office on casio
  _maps/map_files/CasioStation/Casiostation.dmm
Labels: Map Things, Tweak

#614 Remora updates
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Fix

#618 Update Sci Protolathe - Syringes and Droppers
  code/modules/research/designs/autolathe_designs.dm
Labels: Tweak, Xan seal of approval (not trademarked), quality of life

#623 Updating Fermistation part 12 pain edition
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things, Fix, quality of life

#624 HOP now spawns with a random funny ID
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrites.dm
  ModularBungalow/ids.dm
  ModularBungalow/zbungalowicons/card.dmi
  icons/obj/card.dmi
  tgstation.dme
Labels: Feature, Speedmerge, Sprites

#625 Glove and Jackboots change (that I consider a fix)
  ModularBungalow/vending_machine_edits.dm
  code/modules/clothing/gloves/color.dm
  code/modules/jobs/job_types/detective.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#626 Autolathe now accepts plastic
  code/datums/materials/basemats.dm
  html/changelogs/Kalesonki-PR-626.yml
Labels: Fix

#627 ChemRe ID fix
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Fix

#628 small fix
  ModularBungalow/bungalow_food_and_drinks/drinks.dm
Labels: Speedmerge, Fix

#615 Maprotation will no longer pick the same map twice
  code/controllers/subsystem/mapping.dm
Labels: DO NOT MERGE, Tweak, Admin

#635 Adds new tip
  strings/tips.txt
Labels: Speedmerge, Tweak
