Repository Quasar-13/Quasar-13, pull requests merged in 2022-01, with the labels that each got.

#405 Swaps command chat to Silver, as god intended.
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/constants.js
Labels: Tweak

#413 Changes flashlight sprite
  icons/obj/lighting.dmi
Labels: Speedmerge, Sprites

#414 Adds Grinder to pubbystation Xenobio
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Things, Speedmerge, Tweak

#415 Big Shot Glasses
  code/modules/clothing/glasses/_glasses.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprites

#398 Rockplanet And Jungle Mining 2 Electric Boogaloo
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  ModularBungalow/mobs/megafauna/rockplanet/markedone/blade.dmi
  ModularBungalow/mobs/megafauna/rockplanet/markedone/bladehandsleft.dmi
  ModularBungalow/mobs/megafauna/rockplanet/markedone/bladehandsright.dmi
  ModularBungalow/mobs/megafauna/rockplanet/markedone/items.dm
  ModularBungalow/mobs/megafauna/rockplanet/markedone/megafauna.dm
  ModularBungalow/mobs/megafauna/rockplanet/markedone/mob.dmi
  ModularBungalow/mobs/megafauna/rockplanet/platinumangel/items.dm
  ModularBungalow/mobs/megafauna/rockplanet/platinumangel/megafauna.dm
  ModularBungalow/mobs/megafauna/rockplanet/platinumangel/mob.dmi
  _maps/RandomRuins/IceRuins/icemoon_underground_crystal.dmm
  _maps/RandomRuins/JungleRuins/jungle_leaper.dmm
  _maps/RandomRuins/JungleRuins/jungle_syndicate.dmm
  _maps/RandomRuins/RockRuins/rockplanet_marked.dmm
  _maps/RandomRuins/RockRuins/rockplanet_platinum.dmm
  code/datums/ruins/jungle.dm
  code/datums/ruins/rockplanet.dm
  code/game/objects/items/devices/gps.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
  tgstation.dme
Labels: Feature, Map Things

#412 Guncrafting V1 & Casiostation Fixes
  ModularBungalow/bungalowWeapons/_icon/crafting.dmi
  ModularBungalow/bungalowWeapons/energy.dm
  ModularBungalow/bungalowWeapons/guns/energy/SX.dm
  ModularBungalow/bungalowWeapons/guns/energy/energy.dm
  ModularBungalow/bungalowWeapons/gunsmithing/kits.dm
  ModularBungalow/bungalowWeapons/gunsmithing/nopins.dm
  ModularBungalow/bungalowWeapons/gunsmithing/recipes.dm
  ModularBungalow/clothing/icons/under.dmi
  ModularTegustation/tegu_jobs/gamemode_overwrite.dm
  _maps/map_files/CasioStation/Casiostation.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/construction.dm
  code/datums/components/crafting/crafting.dm
  code/modules/jobs/job_types/!casio/blueshield.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  tgstation.dme
Labels: Feature, Map Things, Fix

#419 Changes VT icons
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Sprites

#418 Adds in Ancient Hardsuits to Pubby
  ModularBungalow/suitstorage.dm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  icons/mob/clothing/suit.dmi
  tgstation.dme
Labels: Tweak

#422 More shirts.
  ModularBungalow/clothing/underwear.dm
  ModularBungalow/clothing/worn/underwearw.dmi
Labels: Fix, Sprites

#423 Adds airtight flaps to cargo shuttle belt on remora station.
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Speedmerge, Tweak

#417 Lavaland Nerfs V1 - Armor
  code/modules/clothing/suits/cloaks.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance

#424 Changes visibility of the silicon's binary chat.
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Labels: Speedmerge, Tweak

#425 Fixes minor mapping issues on Remora Station.
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Speedmerge, Tweak

#426 Adds a janitor ruin on remora station
  _maps/map_files/RemoraStation/RemoraStation.dmm
  code/modules/paperwork/paper_premade.dm
Labels: Map Things, Tweak

#428 Adds atmos to Remora's toxin shuttle
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Speedmerge, Tweak

#429 Adds cat AI core
  code/_globalvars/lists/flavor_misc.dm
  icons/mob/ai.dmi
Labels: Speedmerge, Sprites

#436 Adds Tomb Worlds to Tidalmoon
  _maps/map_files/Mining/Tidalmoon.dmm
Labels: Map Things, Tweak

#432 Mining guns v2
  ModularBungalow/bungalowWeapons/_icon/miningguns.dmi
  ModularBungalow/bungalowWeapons/guns/energy/mining.dm
  code/modules/mining/machine_vending.dm
Labels: Feature, Speedmerge

#430 Jungle Mob Changes
  code/datums/mapgen/biomes/_biome.dm
Labels: Tweak

#439 Make special area for the bathroom ruin.
  ModularBungalow/areas.dm
  ModularBungalow/clothing/icons/areasb.dmi
  ModularBungalow/sounds/among_Us_Drip_Theme.ogg
  tgstation.dme
Labels: Feature, Map Things, Affront to God, DO NOT MERGE

#440 Devious lick ruin
  _maps/RandomRuins/SpaceRuins/devious_lick.dmm
  code/datums/ruins/space.dm
Labels: Feature, Map Things, Speedmerge, Xan seal of approval (not trademarked)

#444 Makes Big shot modular
  ModularBungalow/clothing/glasses.dm
  ModularBungalow/clothing/icons/glasses.dmi
  ModularBungalow/clothing/worn/glassesw.dmi
  ModularBungalow/vending_Machines.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
  tgstation.dme
Labels: Modular

#437 TerraGov-Brand Disablers
  ModularBungalow/bungalowWeapons/_icon/energy.dmi
  ModularBungalow/bungalowWeapons/guns/energy/TerraGovRiotControl.dm
  ModularBungalow/zbungalowicons/weapons/energy_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/energy_righthand.dmi
  tgstation.dme
Labels: Feature

#431 Gives the AI a shell from roundstart.
  code/controllers/subsystem/ticker.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
Labels: Feature

#452 Testfixing the Alt-jobs
  ModularBungalow/altjobtitles/alt_titles.dm
Labels: Fix

#455 New Ai face.
  code/_globalvars/lists/flavor_misc.dm
  icons/mob/ai.dmi
Labels: Sprites

#458 2 new sports bra.
  ModularBungalow/clothing/underwear.dm
  ModularBungalow/clothing/worn/underwearw.dmi
Labels: Sprites

#459 fix
  ModularBungalow/clothing/underwear.dm
Labels: Fix

#460 Admin maps
  _maps/RandomRuins/admin/cael.dmm
  _maps/RandomRuins/admin/drekar.dmm
  code/datums/ruins/admin.dm
  tgstation.dme
Labels: Map Things

#464 small changes to space cop uniform.
  code/modules/clothing/under/jobs/security.dm
  icons/mob/clothing/under/security.dmi
Labels: Speedmerge, Sprites

#451 Ported Mantis Blades From Yog
  ModularBungalow/bungalowimplants/mantis.dm
  ModularBungalow/zbungalowicons/weapons/melee.dmi
  ModularBungalow/zbungalowicons/weapons/melee_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee_righthand.dmi
  code/game/objects/items/storage/briefcase.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Feature

#470 Secretary figurine
  ModularBungalow/toys.dm
  ModularBungalow/zbungalowicons/toys.dmi
Labels: Sprites

#469 fix sleeping crew monitor bug
  code/game/machinery/computer/crew.dm
Labels: Fix

#443 Adds radio sound effects
  code/game/objects/items/devices/radio/radio.dm
  sound/effects/radio/radio1.ogg
  sound/effects/radio/radio2.ogg
  sound/effects/radio/radio3.ogg
Labels: Feature

#473 I have to make a whole PR for this
  _maps/RandomRuins/admin/drekar.dmm
Labels: Speedmerge, Fix

#475 Fixes sprite issue with Casio hardsuit
  ModularBungalow/clothing/hardsuit.dm
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
Labels: Speedmerge, Fix, Sprites

#476 Minor Spritefix
  icons/obj/pda.dmi
Labels: Speedmerge, Sprites

#433 Ghosts can observe ai laws through its eye.
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Feature

#442 Adds a tab to the supply console that explains some delivery systems and department orders [PORT]
  tgui/packages/tgui/interfaces/Cargo.js
Labels: Gives GBP

#453 Adds new guns. Currently admin only
  ModularBungalow/bungalowWeapons/_icon/ballistics.dmi
  ModularBungalow/bungalowWeapons/ammoboxes.dm
  ModularBungalow/bungalowWeapons/guns/ballistics.dm
  ModularBungalow/bungalowWeapons/guns/revolver.dm
Labels: Feature, Sprites

#463 You can now emag a PAI [TG Port]
  code/modules/mob/living/silicon/pai/pai.dm
Labels: Feature

#481 im dumb. (fix for real)
  ModularBungalow/clothing/underwear.dm
Labels: Fix

#480 Beacon Fix
  ModularBungalow/bungalow_beacon.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Fix

#457 Adds centcom test chamber from yog
  _maps/map_files/generic/CentCom.dmm
  code/game/area/areas/centcom.dm
Labels: Map Things

#478 baseball bat with a Toolbox
  ModularBungalow/melee_weapons.dm
  ModularBungalow/recipes.dm
  ModularBungalow/zbungalowicons/weapons/melee.dmi
  ModularBungalow/zbungalowicons/weapons/melee_lefthand.dmi
  ModularBungalow/zbungalowicons/weapons/melee_righthand.dmi
  code/game/objects/items/weaponry.dm
  tgstation.dme
Labels: Feature

#477 Adds metal cage for storing mice
  code/game/objects/items/pet_carrier.dm
  icons/mob/clothing/suit.dmi
  icons/obj/pet_carrier.dmi
Labels: Feature

#484 adds a centcom backpack
  code/game/objects/items/storage/backpack.dm
  icons/mob/clothing/back.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites

#485 Adds new Uniforms, Outfits, Cloaks and more
  ModularBungalow/clothing/cloak.dm
  ModularBungalow/clothing/coat.dm
  ModularBungalow/clothing/icons/cloak.dmi
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/icons/suits.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/suits.dm
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/cloakw.dmi
  ModularBungalow/clothing/worn/coatw.dmi
  ModularBungalow/clothing/worn/paradew.dmi
  ModularBungalow/clothing/worn/suitsw.dmi
  ModularBungalow/clothing/worn/underw.dmi
  code/modules/clothing/outfits/standard.dm
  code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
  code/modules/vending/wardrobes.dm
  icons/mob/human_parts_greyscale.dmi
Labels: Feature, Sprites

#474 Adds Fermistation
  _maps/_basemap.dm
  _maps/fermistation.json
  _maps/map_files/Fermistation/Fermistation.dmm
  config/maps.txt
Labels: Feature, Map Things

#486 Modular this modualr that
  ModularBungalow/clothing/back.dm
  ModularBungalow/clothing/icons/back.dmi
  ModularBungalow/clothing/worn/backw.dmi
  ModularBungalow/vending_Machines.dm
  ModularBungalow/zbungalowicons/clothes_lefthand.dmi
  ModularBungalow/zbungalowicons/clothes_righthand.dmi
  code/game/objects/items/storage/backpack.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/back.dmi
  icons/obj/storage.dmi
  tgstation.dme
Labels: Cleanup, Modular

#488 Secretary have they own Briefcase.
  ModularBungalow/clothing/back.dm
  ModularBungalow/clothing/icons/back.dmi
  ModularBungalow/clothing/icons/storage.dmi
  ModularBungalow/clothing/storage.dm
  ModularBungalow/zbungalowicons/clothes_lefthand.dmi
  ModularBungalow/zbungalowicons/clothes_righthand.dmi
  ModularBungalow/zbungalowicons/items_lefthand.dmi
  ModularBungalow/zbungalowicons/items_righthand.dmi
  code/modules/jobs/job_types/secretary.dm
  tgstation.dme
Labels: Sprites

#487 Slightly more outfits
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/icons/coat.dmi
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/icons/under.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/under.dm
  ModularBungalow/clothing/worn/paradew.dmi
  ModularBungalow/clothing/worn/underw.dmi
  ModularBungalow/lawyeritem.dm
  ModularBungalow/zbungalowicons/objects.dmi
  code/modules/clothing/outfits/standard.dm
Labels: Feature, Sprites

#495 Adds in NT Navy rank ribbons
  ModularBungalow/clothing/accessory.dm
  ModularBungalow/clothing/icons/accessory.dmi
Labels: Sprites, Lore

#496 Pins Part 2 Electric Boogaloo
  ModularBungalow/altjobtitles/outfits.dm
  ModularBungalow/clothing/accessory.dm
  ModularBungalow/clothing/worn/accessoryw.dmi
  ModularBungalow/lawyeritem.dm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/job_types/!blacksite/bridge.dm
  code/modules/jobs/job_types/!blacksite/deathsquad.dm
  code/modules/jobs/job_types/!blacksite/ertcommander.dm
  code/modules/jobs/job_types/!blacksite/ertengineer.dm
  code/modules/jobs/job_types/!blacksite/ertmedic.dm
  code/modules/jobs/job_types/!blacksite/ertsecurity.dm
  code/modules/jobs/job_types/!blacksite/ntcommander.dm
  code/modules/jobs/job_types/!blacksite/ntleader.dm
  code/modules/jobs/job_types/!blacksite/ntmedical.dm
  icons/mob/clothing/accessories.dmi
Labels: Speedmerge, Fix, Sprites

#491 Fixes techcult ruin computers.
  _maps/RandomRuins/IceRuins/icemoon_underground_techcult.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_techcult.dmm
Labels: Map Things

#497 Replaces Pulse Gun Tasers with NeoTasers
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/projectile/energy/taser.dm
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Feature, Test Merged, Balance

#501 fixes some runtimes of duplicate lattices/catwalks on maps
  ModularBungalow/ruins/interdyne.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/CasioStation/Casiostation_old.dmm
  _maps/map_files/GalaxyStation/Galaxystation.dmm
  _maps/map_files/Mining/Tidalmoon.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  _maps/map_files/RemoraStation/RemoraStation.dmm
Labels: Map Things, Fix

#370 Random antagonist job restrictions removal
  ModularTegustation/tegu_config.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/traitor/traitor.dm
  config/game_options.txt
Labels: Feature, Kirie Seal Of Approval (trademarked)

#503 r u n t i m e s
  _maps/map_files/CasioStation/Casiostation.dmm
  _maps/map_files/CasioStation/Casiostation_old.dmm
  _maps/map_files/ChimeraStation/ChimeraStation.dmm
  _maps/map_files/GalaxyStation/Galaxystation.dmm
Labels: Map Things, Fix

#505 Removes the buffs that where giveng to felinids.
  code/modules/mob/living/carbon/human/species_types/felinid.dm
Labels: Speedmerge, Balance

#506 ports: Re-adds the admin button to let them exempt players from job exp requirements.
  code/modules/admin/topic.dm
  code/modules/jobs/job_report.dm
  tgui/packages/tgui/interfaces/TrackedPlaytime.js
Labels: Speedmerge, admin

#507 ports 64363 and 64382
  code/modules/events/spacevine.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Speedmerge, Sprites, quality of life

#468 Bumps bootstrapped python to 3.7.9
  dependencies.sh
  tools/bootstrap/python37._pth
  tools/bootstrap/python_.ps1
  tools/requirements.txt
Labels: Needs Headcoder Approval

#513 Re-adds space russiand and little cleanup
  ModularBungalow/bungalow_languages/icons/language_icons.dmi
  ModularBungalow/bungalow_languages/language_books.dm
  ModularBungalow/bungalow_languages/languages/beecommon.dm
  ModularBungalow/bungalow_languages/languages/russian.dm
  ModularBungalow/bungalow_languages/languages/spacer.dm
  code/modules/language/beecommon.dm
  code/modules/language/language_holder.dm
  code/modules/surgery/organs/tongue.dm
  icons/misc/language.dmi
  tgstation.dme
Labels: Cleanup

#514 fixes nukies getting weird codes (maybe)
  _maps/map_files/generic/CentCom.dmm
Labels: Map Things, Fix

#489 ports https://github.com/Skyrat-SS13/Skyrat-tg/pull/1996 (paycheck)
  code/__DEFINES/economy.dm
  code/controllers/subsystem/economy.dm
Labels: Feature

#490 Adds jungle techcult ruin.
  _maps/RandomRuins/JungleRuins/jungle_techcult.dmm
  code/modules/ruins/lavalandruin_code/techcult.dm
Labels: Map Things

#511 Bloons TD6 in SS13
  code/game/objects/items/toys.dm
Labels: Feature

#512 Buffs RD
  ModularBungalow/bungalow_config_and_global_lists/overwrites.dm
Labels: Speedmerge, Tweak, Balance, Merge conflict

#517 Fixes beacons
  ModularBungalow/bungalow_beacon.dm
  ModularBungalow/clothing/storage.dm
  code/modules/jobs/job_types/!blacksite/deathsquad.dm
  code/modules/jobs/job_types/!blacksite/ertcommander.dm
  code/modules/jobs/job_types/!blacksite/ertengineer.dm
  code/modules/jobs/job_types/!blacksite/ertmedic.dm
  code/modules/jobs/job_types/!blacksite/ertsecurity.dm
  code/modules/jobs/job_types/!blacksite/ntleader.dm
  code/modules/jobs/job_types/!blacksite/ntmarine.dm
Labels: Speedmerge, Fix

#518 Updating Fermistation part 6
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things, Fix

#519 Adds in two more admiral outfits
  ModularBungalow/clothing/accessory.dm
  ModularBungalow/clothing/icons/accessory.dmi
  ModularBungalow/clothing/icons/parade.dmi
  ModularBungalow/clothing/parade.dm
  ModularBungalow/clothing/worn/paradew.dmi
  code/modules/clothing/outfits/standard.dm
Labels: Speedmerge, Sprites, Lore

#494 [PORT] Drugs of the 26th century. Three new hella rad drugs, one less lame drug and more!
  _maps/RandomRuins/SpaceRuins/smallsphere.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/reagents.dm
  code/__DEFINES/sound.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_globalvars/traits.dm
  code/datums/diseases/adrenal_crisis.dm
  code/datums/emotes.dm
  code/datums/quirks/negative.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/drug_items.dm
  code/game/objects/items/maintenance_loot.dm
  code/modules/actionspeed/modifiers/drugs.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/cargo/bounties/reagent.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/grown/kronkus.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  icons/mob/human_parts.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/drugs.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/maintenance_loot.dmi
  sound/chemistry/saturnx_fade.ogg
  sound/items/ampoule_snap.ogg
  tgstation.dme
Labels: Feature

#523 good ass stupid TG have broken sprites
  code/game/objects/items/handcuffs.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
Labels: Sprites

#525 Update tips.txt
  strings/tips.txt
Labels: Tweak

#529 Reverts to old beacons
  ModularBungalow/Secure_lockers.dm
  ModularBungalow/SecuritySpecialist/mechpilot.dm
  ModularBungalow/SecuritySpecialist/specialist.dm
  ModularBungalow/bungalow_beacon.dm
  ModularBungalow/clothing/storage.dm
  _maps/RandomRuins/admin/drekar.dmm
  _maps/templates/drekar.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/!blacksite/ntleader.dm
  code/modules/jobs/job_types/!blacksite/ntmarine.dm
Labels: Fix

#531 Update Fermistation.dmm
  _maps/map_files/Fermistation/Fermistation.dmm
Labels: Map Things, Fix

#533 a simulation, INSIDE, of a simulation! NTSL updates
  ModularBungalow/NTSL/code/modules/scripting/Implementations/Telecomms.dm
  ModularBungalow/NTSL/code/modules/scripting/Interpreter/Scope.dm
Labels: Fix, quality of life

#515 move more stuff from tegustation to bungalow
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/bungalow_Weapons/melee_weapons.dm
  ModularBungalow/bungalow_configs_and_stuff/config.dm
  ModularBungalow/bungalow_configs_and_stuff/global_list.dm
  ModularBungalow/bungalow_configs_and_stuff/integration.dm
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwerites_vars.dm
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrite_gamemode.dm
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrites.dm
  ModularBungalow/bungalow_configs_and_stuff/overwrites/overwrites_hud.dm
  ModularBungalow/bungalow_configs_and_stuff/procs.dm
  ModularBungalow/bungalow_configs_and_stuff/trusted.dm
  ModularBungalow/bungalow_configs_and_stuff/world.dm
  ModularBungalow/bungalow_organs_and_implants/looc.dm
  ModularBungalow/cargo/blackmarket.dm
  ModularBungalow/cargo/bounties.dm
  ModularBungalow/cargo/goodies.dm
  ModularBungalow/cargo/newinstances.dm
  ModularBungalow/cargo/packs.dm
  ModularBungalow/clothing/wintercoats.dm
  ModularBungalow/medicine/virology/sympthons_and_disease.dm
  ModularBungalow/ruins/bungalow_ruins.dm
  ModularBungalow/shuttles.dm
  ModularBungalow/startfurry_event.dm
  ModularTegustation/tegu_weapons/rifles.dm
  ModularTegustation/tegu_weapons/tegumelee.dm
  ModularTegustation/tegu_weapons/tegupistols.dm
  ModularTegustation/tegushuttles.dm
  ModularTegustation/zTegu_overwrite/cards.dm
  tgstation.dme
Labels: Cleanup

#535 brings the span folder from yog to our codebase
  code/__DEFINES/span.dm
Labels: Feature

#532 Computer sprite improvments
  ModularTegustation/tegu_rmbk/code/modules/power/reactor/rbmk.dm
  code/game/machinery/bank_machine.dm
  goon/icons/obj/goon_terminals.dmi
  icons/obj/computer.dmi
Labels: Fix, Sprites

#537 fixes span merge
  tgstation.dme
Labels: Fix
