Repository Quasar-13/Quasar-13, pull requests merged in 2022-06, with the labels that each got.

#759 HOP Returns to cargo
  code/modules/jobs/job_types/head_of_personnel.dm
Labels: Speedmerge, Tweak, Balance

#761 Jungleplanet Minor Fixes
  _maps/map_files/Mining/Jungle.dmm
Labels: Fix

#758 Final Captain gun: L-204 Melter
  ModularBungalow/bungalow_beacon.dm
Labels: Feature

#762 Miasma generation increase and New Symptom fix
  ModularBungalow/medicine/virology/buffs.dm
  ModularBungalow/medicine/virology/healing.dm
  code/__DEFINES/atmospherics.dm
Labels: Tweak, Balance

#764 The Walkway
  _maps/map_files/CasioStation/Casiostation.dmm
Labels: Map Things, Fix

#760 Removes the Axe from the asteroid base
  _maps/map_files/Mining/Asteroidbelt.dmm
Labels: Tweak

#763 Rockplanet Mob Rebalance, and Arlem Nerf
  ModularBungalow/Mining/rockplanet.dm
  ModularBungalow/mobs/megafauna/rockplanet/arlem/megafauna.dm
Labels: Balance

#767 Romulus facility update v7
  ModularBungalow/bungalow_Weapons/_icon/ammo_box.dmi
  ModularBungalow/bungalow_Weapons/_icon/ballistics.dmi
  ModularBungalow/bungalow_Weapons/ammoboxes.dm
  ModularBungalow/bungalow_Weapons/ammocasing/pistol.dm
  ModularBungalow/bungalow_Weapons/ammocasing/rifle.dm
  ModularBungalow/bungalow_Weapons/ammocasing/rocket.dm
  ModularBungalow/bungalow_Weapons/ballistic/explosive.dm
  ModularBungalow/bungalow_Weapons/ballistic/pistol_and_revolvers.dm
  ModularBungalow/bungalow_Weapons/ballistic/rifle.dm
  ModularBungalow/bungalow_Weapons/ballistic/smgs.dm
  ModularBungalow/clothing/icons/pouch.dmi
  ModularBungalow/project_kepler/clothing.dm
  ModularBungalow/project_kepler/items.dm
  ModularBungalow/project_kepler/militarykits.dm
  _maps/map_files/RomulusFacility/RomulusFacility.dmm
  code/__DEFINES/projectiles.dm
  code/modules/jobs/job_types/!extra/kepler/ice/!outfits.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Project Kepler

#769 Kills Mining Traitor
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/traitor/traitor.dm
Labels: Balance, Host Approval

#771 Adds Pinlocked Trait to Miner Guns
  ModularBungalow/bungalow_Weapons/Energy/sniper.dm
  ModularBungalow/bungalow_Weapons/series/mining.dm
  code/modules/projectiles/gun.dm
Labels: Feature, Balance

#770 The Atmos Tech outfit expansion
  ModularBungalow/altjobtitles/outfits.dm
Labels: Feature

#772 Jungle is slightly less CBT
  ModularBungalow/bungalow_Weapons/_icon/miningguns.dmi
  ModularBungalow/bungalow_Weapons/series/mining.dm
  _maps/map_files/Mining/Jungle.dmm
Labels: Fix, Quality of Life

#765 Rad Storm Minor tweaks
  _maps/map_files/CasioStation/Casiostation.dmm
  code/datums/weather/weather_types/radiation_storm.dm
  code/modules/events/radiation_storm.dm
Labels: Tweak

#776 Removes Fermistation
  _maps/_basemap.dm
  _maps/fermistation.json
  _maps/map_files/Fermistation/Fermistation.dmm
  config/maps.txt
Labels: Removal

#777 Blue helmets resprites
  ModularBungalow/clothing/berets.dm
  ModularBungalow/clothing/helmet.dm
  ModularBungalow/clothing/icons/beret.dmi
  ModularBungalow/clothing/icons/helmet.dmi
  ModularBungalow/clothing/worn/beretw.dmi
  ModularBungalow/clothing/worn/helmetw.dmi
  ModularBungalow/mobs/infectedspawner.dm
  ModularBungalow/mobs/solgov.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/simple_human.dmi
Labels: Sprites, Project Kepler
